
CliqueDB = {
	["char"] = {
	},
	["profileKeys"] = {
		["Unlok - Auchindoun"] = "Unlok - Auchindoun",
		["Ciid - Hellscream"] = "Ciid - Hellscream",
		["Irone - Hellscream"] = "Irone - Hellscream",
		["Chukk - Auchindoun"] = "Chukk - Auchindoun",
		["Zik - Zuluhed"] = "Zik - Zuluhed",
		["Karrl - Auchindoun"] = "Karrl - Auchindoun",
		["Gacrux - Thorium Brotherhood"] = "Gacrux - Thorium Brotherhood",
		["Relok - Auchindoun"] = "Relok - Auchindoun",
		["Promitto - Auchindoun"] = "Promitto - Auchindoun",
		["Tamori - ChaosWoW Funserver"] = "Tamori - ChaosWoW Funserver",
		["Pulari - Auchindoun"] = "Pulari - Auchindoun",
		["Totemtusk - Auchindoun"] = "Totemtusk - Auchindoun",
		["Freezeforu - Zuluhed"] = "Freezeforu - Zuluhed",
		["Carrl - Auchindoun"] = "Carrl - Auchindoun",
		["Scid - Auchindoun"] = "Scid - Auchindoun",
		["Japhaar - Hellscream"] = "Japhaar - Hellscream",
		["Gacrux - Zuluhed"] = "Gacrux - Zuluhed",
		["Chukk - Hellscream"] = "off",
		["Wezen - Thorium Brotherhood"] = "Wezen - Thorium Brotherhood",
		["Aonah - Auchindoun"] = "Aonah - Auchindoun",
		["Pandohra - Auchindoun"] = "Pandohra - Auchindoun",
		["Gacrux - Auchindoun"] = "Gacrux - Auchindoun",
		["Barimuri - Hellscream"] = "Barimuri - Hellscream",
		["Tolate - Hellscream"] = "Tolate - Hellscream",
		["Wezen - Auchindoun"] = "Wezen - Auchindoun",
		["Xanaomi - Hellscream"] = "Xanaomi - Hellscream",
		["Yttrium - Auchindoun"] = "Yttrium - Auchindoun",
		["Aset - Auchindoun"] = "Aset - Auchindoun",
		["Bairra - Alterac valley (PVP - INSTA 70)"] = "Bairra - Alterac valley (PVP - INSTA 70)",
		["Knas - Auchindoun"] = "Knas - Auchindoun",
		["Promitto - Thorium Brotherhood"] = "Promitto - Thorium Brotherhood",
	},
	["profiles"] = {
		["Zik - Zuluhed"] = {
			["clicksets"] = {
				["Default"] = {
					["2"] = {
						["arg2"] = "Rank 2",
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 2,
						["arg1"] = "Holy Light",
						["texture"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
					},
				},
			},
		},
		["Ciid - Hellscream"] = {
			["clicksets"] = {
				["Default"] = {
					["3"] = {
						["arg2"] = "Rank 9",
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 3,
						["delete"] = true,
						["arg1"] = "Rejuvenation",
						["texture"] = "Interface\\Icons\\Spell_Nature_Rejuvenation",
					},
					["Shift-1"] = {
						["arg2"] = "Rank 12",
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 1,
						["arg1"] = "Healing Touch",
						["texture"] = "Interface\\Icons\\Spell_Nature_HealingTouch",
					},
					["Shift-2"] = {
						["arg2"] = "Rank 9",
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 2,
						["arg1"] = "Regrowth",
						["texture"] = "Interface\\Icons\\Spell_Nature_ResistNature",
					},
					["2"] = {
						["arg2"] = "Rank 1",
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 2,
						["arg1"] = "Lifebloom",
						["texture"] = "Interface\\Icons\\INV_Misc_Herb_Felblossom",
					},
					["Shift-3"] = {
						["arg2"] = "",
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 3,
						["arg1"] = "Swiftmend",
						["texture"] = "Interface\\Icons\\INV_Relics_IdolofRejuvenation",
					},
				},
			},
			["blacklist"] = {
				["PitBullCluster2UnitButton4"] = true,
				["TargetFrame"] = true,
				["PitBullCluster2UnitButton1"] = true,
				["PitBullCluster3UnitButton1"] = true,
				["PitBullUnitFrame2"] = true,
				["PitBullUnitFrame1"] = true,
				["PitBullCluster2UnitButton2"] = true,
				["PitBullUnitFrame3"] = true,
				["PitBullCluster1UnitButton1"] = true,
				["PitBullCluster1UnitButton2"] = true,
				["PlayerFrame"] = true,
				["PitBullUnitFrame6"] = true,
				["PitBullUnitFrame4"] = true,
				["PitBullUnitFrame5"] = true,
				["PitBullUnitFrame7"] = true,
				["PitBullCluster1UnitButton3"] = true,
				["PitBullCluster2UnitButton3"] = true,
				["PitBullCluster1UnitButton4"] = true,
				["TargetofTargetFrame"] = true,
			},
		},
		["Irone - Hellscream"] = {
		},
		["Relok - Auchindoun"] = {
		},
		["Aonah - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "3",
						["arg1"] = "Remove Curse",
						["texture"] = "Interface\\Icons\\Spell_Nature_RemoveCurse",
					},
				},
			},
		},
		["Japhaar - Hellscream"] = {
		},
		["Barimuri - Hellscream"] = {
		},
		["off"] = {
			["clicksets"] = {
				["Default"] = {
					["Ctrl-1"] = {
						["arg2"] = "",
						["type"] = "spell",
						["modifier"] = "Ctrl-",
						["button"] = 1,
						["arg1"] = "Pain Suppression",
						["texture"] = "Interface\\Icons\\Spell_Holy_PainSupression",
					},
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 3,
						["delete"] = true,
						["arg1"] = "Renew",
						["texture"] = "Interface\\Icons\\Spell_Holy_Renew",
					},
					["Shift-1"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 1,
						["delete"] = true,
						["arg1"] = "Power Word: Shield",
						["texture"] = "Interface\\Icons\\Spell_Holy_PowerWordShield",
					},
					["Shift-2"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Flash Heal",
						["texture"] = "Interface\\Icons\\Spell_Holy_FlashHeal",
					},
					["Ctrl-2"] = {
						["arg2"] = "",
						["type"] = "spell",
						["modifier"] = "Ctrl-",
						["button"] = 2,
						["arg1"] = "Power Infusion",
						["texture"] = "Interface\\Icons\\Spell_Holy_PowerInfusion",
					},
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Greater Heal",
						["texture"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
					},
					["Shift-3"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 3,
						["delete"] = true,
						["arg1"] = "Prayer of Mending",
						["texture"] = "Interface\\Icons\\Spell_Holy_PrayerOfMendingtga",
					},
				},
			},
			["blacklist"] = {
				["PartyMemberFrame2"] = true,
				["PetFrame"] = true,
				["PartyMemberFrame4"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PartyMemberFrame1"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["PartyMemberFrame3"] = true,
				["TargetFrame"] = true,
				["TargetofTargetFrame"] = true,
			},
		},
		["Aset - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "2",
						["arg1"] = "Rejuvenation",
						["texture"] = "Interface\\Icons\\Spell_Nature_Rejuvenation",
					},
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "3",
						["arg1"] = "Nourish",
						["texture"] = "Interface\\Icons\\Ability_Druid_Nourish",
					},
					["Shift-1"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "1",
						["arg1"] = "Lifebloom",
						["texture"] = "Interface\\Icons\\INV_Misc_Herb_Felblossom",
					},
					["5"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "5",
						["arg1"] = "Abolish Poison",
						["texture"] = "Interface\\Icons\\Spell_Nature_NullifyPoison_02",
					},
					["4"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "4",
						["arg1"] = "Remove Curse",
						["texture"] = "Interface\\Icons\\Spell_Holy_RemoveCurse",
					},
					["Shift-2"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "2",
						["arg1"] = "Regrowth",
						["texture"] = "Interface\\Icons\\Spell_Nature_ResistNature",
					},
					["Shift-3"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 3,
						["delete"] = true,
						["arg1"] = "Swiftmend",
						["texture"] = "Interface\\Icons\\INV_Relics_IdolofRejuvenation",
					},
				},
			},
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnitfocustarget"] = true,
				["IceHUD_TargetInfo"] = true,
				["TargetFrameToT"] = true,
				["PitBullUnitFrame6"] = true,
				["FocusFrame"] = true,
				["IceHUD_PlayerInfo"] = true,
				["Boss3TargetFrame"] = true,
				["PitBullUnitFrame1"] = true,
				["PetFrame"] = true,
				["PitBullUnitFrame3"] = true,
				["PartyMemberFrame4"] = true,
				["PitBullCluster1UnitButton2"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PitBullUnitFrame7"] = true,
				["PitBullCluster1UnitButton3"] = true,
				["Boss4TargetFrame"] = true,
				["PitBullCluster1UnitButton1"] = true,
				["SUFUnittargettarget"] = true,
				["PartyMemberFrame2"] = true,
				["PitBull4_Frames_pet"] = true,
				["FocusFrameToT"] = true,
				["TargetFrame"] = true,
				["PitBullCluster2UnitButton1"] = true,
				["Boss2TargetFrame"] = true,
				["PitBullUnitFrame4"] = true,
				["PitBullUnitFrame2"] = true,
				["SUFUnitplayer"] = true,
				["Boss1TargetFrame"] = true,
				["IceHUD_PetInfo"] = true,
				["SUFUnitfocus"] = true,
				["PitBull4_Frames_targettarget"] = true,
				["PitBullCluster2UnitButton2"] = true,
				["PitBull4_Frames_target"] = true,
				["PitBull4_Frames_pettarget"] = true,
				["PitBull4_Frames_focus"] = true,
				["PitBullCluster2UnitButton3"] = true,
				["IceHUD_TargetOfTarget"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PitBullUnitFrame5"] = true,
				["PartyMemberFrame3"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame1"] = true,
				["TargetofTargetFrame"] = true,
			},
		},
		["Promitto - Thorium Brotherhood"] = {
			["clicksets"] = {
				["Default"] = {
					["Shift-2"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "2",
						["arg1"] = "Holy Light",
						["texture"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
					},
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "2",
						["arg1"] = "Flash of Light",
						["texture"] = "Interface\\Icons\\Spell_Holy_FlashHeal",
					},
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "3",
						["delete"] = true,
						["arg1"] = "Purify",
						["texture"] = "Interface\\Icons\\Spell_Holy_Purify",
					},
					["Shift-1"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "1",
						["arg1"] = "Righteous Defense",
						["texture"] = "Interface\\Icons\\INV_Shoulder_37",
					},
				},
			},
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnittargettarget"] = true,
				["PartyMemberFrame2"] = true,
				["SUFUnitfocustarget"] = true,
				["FocusFrameToT"] = true,
				["TargetFrame"] = true,
				["Boss1TargetFrame"] = true,
				["Boss2TargetFrame"] = true,
				["TargetFrameToT"] = true,
				["PartyMemberFrame1"] = true,
				["FocusFrame"] = true,
				["Boss3TargetFrame"] = true,
				["SUFUnitfocus"] = true,
				["PartyMemberFrame3"] = true,
				["PetFrame"] = true,
				["PartyMemberFrame4"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["SUFUnitpet"] = true,
				["Boss4TargetFrame"] = true,
				["SUFUnitplayer"] = true,
			},
		},
		["Unlok - Auchindoun"] = {
		},
		["Chukk - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["Ctrl-2"] = {
						["type"] = "spell",
						["modifier"] = "Ctrl-",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Dispel Magic",
						["texture"] = "Interface\\Icons\\Spell_Holy_DispelMagic",
					},
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 3,
						["delete"] = true,
						["arg1"] = "Renew",
						["texture"] = "Interface\\Icons\\Spell_Holy_Renew",
					},
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Flash Heal",
						["texture"] = "Interface\\Icons\\Spell_Holy_FlashHeal",
					},
					["Ctrl-3"] = {
						["type"] = "spell",
						["modifier"] = "Ctrl-",
						["button"] = 3,
						["delete"] = true,
						["arg1"] = "Prayer of Mending",
						["texture"] = "Interface\\Icons\\Spell_Holy_PrayerOfMendingtga",
					},
					["4"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "4",
						["arg1"] = "Abolish Disease",
						["texture"] = "Interface\\Icons\\Spell_Nature_NullifyDisease",
					},
					["Shift-3"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 3,
						["delete"] = true,
						["arg1"] = "Power Word: Shield",
						["texture"] = "Interface\\Icons\\Spell_Holy_PowerWordShield",
					},
					["Ctrl-1"] = {
						["type"] = "spell",
						["modifier"] = "Ctrl-",
						["button"] = "1",
						["delete"] = true,
						["arg1"] = "Prayer of Healing",
						["texture"] = "Interface\\Icons\\Spell_Holy_PrayerOfHealing02",
					},
					["Alt-2"] = {
						["type"] = "spell",
						["modifier"] = "Alt-",
						["button"] = "2",
						["delete"] = true,
						["arg1"] = "Binding Heal",
						["texture"] = "Interface\\Icons\\Spell_Holy_BlindingHeal",
					},
					["Shift-2"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Greater Heal",
						["texture"] = "Interface\\Icons\\Spell_Holy_GreaterHeal",
					},
					["Alt-3"] = {
						["type"] = "spell",
						["modifier"] = "Alt-",
						["button"] = "3",
						["delete"] = true,
						["arg1"] = "Abolish Disease",
						["texture"] = "Interface\\Icons\\Spell_Nature_NullifyDisease",
					},
					["Shift-1"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "1",
						["arg1"] = "Circle of Healing",
						["texture"] = "Interface\\Icons\\Spell_Holy_CircleOfRenewal",
					},
					["5"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "5",
						["arg1"] = "Dispel Magic",
						["texture"] = "Interface\\Icons\\Spell_Holy_DispelMagic",
					},
				},
			},
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnitfocustarget"] = true,
				["IceHUD_TargetInfo"] = true,
				["SUFHeaderpartyUnitButton2"] = true,
				["FocusFrame"] = true,
				["Boss3TargetFrame"] = true,
				["PartyMemberFrame3"] = true,
				["PitBull4_Groups_PartyUnitButton3"] = true,
				["IceHUD_TargetOfTarget"] = true,
				["PartyMemberFrame4"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PitBull4_Groups_PartyUnitButton4"] = true,
				["PitBull4_Frames_targettarget"] = true,
				["Boss4TargetFrame"] = true,
				["PitBull4_Frames_pettarget"] = true,
				["SUFUnittargettarget"] = true,
				["PartyMemberFrame2"] = true,
				["PitBull4_Frames_pet"] = true,
				["SUFHeaderpartyUnitButton4"] = true,
				["FocusFrameToT"] = true,
				["SUFHeaderpartyUnitButton1"] = true,
				["TargetFrame"] = true,
				["Boss2TargetFrame"] = true,
				["PitBullUnitFrame4"] = true,
				["PitBullUnitFrame2"] = true,
				["TargetFrameToT"] = true,
				["SUFUnitplayer"] = true,
				["SUFUnitfocus"] = true,
				["PitBull4_Groups_PartyUnitButton1"] = true,
				["SUFHeaderpartyUnitButton3"] = true,
				["PitBull4_Frames_target"] = true,
				["PitBullUnitFrame1"] = true,
				["PitBullUnitFrame3"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PitBull4_Groups_PartyUnitButton2"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["PitBullUnitFrame5"] = true,
				["PitBull4_Frames_focus"] = true,
				["PartyMemberFrame1"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PetFrame"] = true,
				["TargetofTargetFrame"] = true,
			},
		},
		["Karrl - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "3",
						["delete"] = true,
						["arg1"] = "Rejuvenation",
						["texture"] = "Interface\\Icons\\Spell_Nature_Rejuvenation",
					},
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "2",
						["delete"] = true,
						["arg1"] = "Healing Touch",
						["texture"] = "Interface\\Icons\\Spell_Nature_HealingTouch",
					},
				},
			},
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnittargettarget"] = true,
				["PartyMemberFrame2"] = true,
				["SUFUnitfocustarget"] = true,
				["FocusFrameToT"] = true,
				["TargetFrame"] = true,
				["Boss1TargetFrame"] = true,
				["Boss2TargetFrame"] = true,
				["TargetFrameToT"] = true,
				["PartyMemberFrame1"] = true,
				["FocusFrame"] = true,
				["Boss3TargetFrame"] = true,
				["SUFUnitfocus"] = true,
				["PartyMemberFrame3"] = true,
				["PetFrame"] = true,
				["PartyMemberFrame4"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["SUFUnitpet"] = true,
				["Boss4TargetFrame"] = true,
				["SUFUnitplayer"] = true,
			},
		},
		["Totemtusk - Auchindoun"] = {
		},
		["Gacrux - Thorium Brotherhood"] = {
		},
		["Carrl - Auchindoun"] = {
		},
		["Scid - Auchindoun"] = {
		},
		["Promitto - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["Ctrl-1"] = {
						["type"] = "spell",
						["modifier"] = "Ctrl-",
						["button"] = "1",
						["delete"] = true,
						["arg1"] = "Beacon of Light",
						["texture"] = "Interface\\Icons\\Ability_Paladin_BeaconofLight",
					},
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "3",
						["arg1"] = "Holy Light",
						["texture"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
					},
					["Shift-1"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "1",
						["arg1"] = "Sacred Shield",
						["texture"] = "Interface\\Icons\\Ability_Paladin_BlessedMending",
					},
					["Shift-2"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Holy Light",
						["texture"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
					},
					["5"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "5",
						["arg1"] = "Cleanse",
						["texture"] = "Interface\\Icons\\Spell_Holy_Renew",
					},
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Flash of Light",
						["texture"] = "Interface\\Icons\\Spell_Holy_FlashHeal",
					},
					["Shift-3"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 3,
						["delete"] = true,
						["arg1"] = "Holy Shock",
						["texture"] = "Interface\\Icons\\Spell_Holy_SearingLight",
					},
				},
			},
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnitfocustarget"] = true,
				["IceHUD_TargetInfo"] = true,
				["TargetFrameToT"] = true,
				["FocusFrame"] = true,
				["IceHUD_PlayerInfo"] = true,
				["Boss3TargetFrame"] = true,
				["PartyMemberFrame3"] = true,
				["PetFrame"] = true,
				["IceHUD_TargetOfTarget"] = true,
				["PartyMemberFrame4"] = true,
				["PitBull4_Frames_player"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["PitBull4_Frames_focustarget"] = true,
				["Boss4TargetFrame"] = true,
				["PitBullCluster1UnitButton1"] = true,
				["SUFUnittargettarget"] = true,
				["PartyMemberFrame2"] = true,
				["PitBull4_Frames_pet"] = true,
				["FocusFrameToT"] = true,
				["TargetFrame"] = true,
				["PitBullCluster2UnitButton1"] = true,
				["Boss2TargetFrame"] = true,
				["PitBullUnitFrame4"] = true,
				["PitBullUnitFrame2"] = true,
				["SUFUnitplayer"] = true,
				["PitBull4_Frames_targettarget"] = true,
				["PitBullUnitFrame3"] = true,
				["SUFUnitfocus"] = true,
				["PitBull4_Groups_PartyUnitButton1"] = true,
				["PitBull4_Frames_pettarget"] = true,
				["PitBull4_Frames_target"] = true,
				["PitBullUnitFrame1"] = true,
				["PitBullUnitFrame5"] = true,
				["PartyMemberFrame1"] = true,
				["PitBull4_Frames_focus"] = true,
				["PitBull4_Frames_targettargettarget"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PitBull4_Groups_Party petsUnitButton1"] = true,
				["PitBull4_Frames_focustargettarget"] = true,
				["SUFHeadermaintankUnitButton1"] = true,
				["Boss1TargetFrame"] = true,
				["TargetofTargetFrame"] = true,
			},
		},
		["Holy"] = {
		},
		["Pulari - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "3",
						["delete"] = true,
						["arg1"] = "Roar of Sacrifice",
						["texture"] = "Interface\\Icons\\Ability_Druid_DemoralizingRoar",
					},
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "2",
						["delete"] = true,
						["arg1"] = "Intervene",
						["texture"] = "Interface\\Icons\\Ability_Hunter_Pet_Turtle",
					},
				},
			},
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnittargettarget"] = true,
				["PartyMemberFrame2"] = true,
				["SUFUnitfocustarget"] = true,
				["FocusFrameToT"] = true,
				["TargetFrame"] = true,
				["Boss1TargetFrame"] = true,
				["Boss2TargetFrame"] = true,
				["TargetFrameToT"] = true,
				["PartyMemberFrame1"] = true,
				["FocusFrame"] = true,
				["Boss3TargetFrame"] = true,
				["SUFUnitfocus"] = true,
				["PartyMemberFrame3"] = true,
				["PetFrame"] = true,
				["PartyMemberFrame4"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["SUFUnitpet"] = true,
				["Boss4TargetFrame"] = true,
				["SUFUnitplayer"] = true,
			},
		},
		["Chukk - Hellscream"] = {
		},
		["Gacrux - Zuluhed"] = {
			["clicksets"] = {
				["Default"] = {
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "2",
						["delete"] = true,
						["arg1"] = "Intervene",
						["texture"] = "Interface\\Icons\\Ability_Warrior_VictoryRush",
					},
				},
			},
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnittargettarget"] = true,
				["PartyMemberFrame2"] = true,
				["SUFUnitfocustarget"] = true,
				["FocusFrameToT"] = true,
				["TargetFrame"] = true,
				["Boss1TargetFrame"] = true,
				["Boss2TargetFrame"] = true,
				["TargetFrameToT"] = true,
				["PartyMemberFrame1"] = true,
				["FocusFrame"] = true,
				["Boss3TargetFrame"] = true,
				["SUFUnitfocus"] = true,
				["PartyMemberFrame3"] = true,
				["PetFrame"] = true,
				["PartyMemberFrame4"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["SUFUnitplayer"] = true,
				["Boss4TargetFrame"] = true,
				["SUFUnitpet"] = true,
			},
		},
		["Freezeforu - Zuluhed"] = {
		},
		["Gacrux - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["Shift-1"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "1",
						["arg1"] = "Intervene",
						["texture"] = "Interface\\Icons\\Ability_Warrior_VictoryRush",
					},
				},
			},
		},
		["Wezen - Thorium Brotherhood"] = {
		},
		["Tolate - Hellscream"] = {
		},
		["Wezen - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "3",
						["arg1"] = "Riptide",
						["texture"] = "Interface\\Icons\\spell_nature_riptide",
					},
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "2",
						["arg1"] = "Lesser Healing Wave",
						["texture"] = "Interface\\Icons\\Spell_Nature_HealingWaveLesser",
					},
					["5"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "5",
						["arg1"] = "Earth Shield",
						["texture"] = "Interface\\Icons\\Spell_Nature_SkinofEarth",
					},
					["4"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = "4",
						["arg1"] = "Cleanse Spirit",
						["texture"] = "Interface\\Icons\\Ability_Shaman_CleanseSpirit",
					},
					["Shift-2"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "2",
						["arg1"] = "Healing Wave",
						["texture"] = "Interface\\Icons\\Spell_Nature_MagicImmunity",
					},
					["Shift-1"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = "1",
						["arg1"] = "Chain Heal",
						["texture"] = "Interface\\Icons\\Spell_Nature_HealingWaveGreater",
					},
				},
			},
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFHeaderbossUnitButton3"] = true,
				["SUFUnitfocustarget"] = true,
				["IceHUD_TargetInfo"] = true,
				["TargetFrameToT"] = true,
				["FocusFrame"] = true,
				["IceHUD_PlayerInfo"] = true,
				["SUFHeaderbossUnitButton1"] = true,
				["Boss3TargetFrame"] = true,
				["PartyMemberFrame3"] = true,
				["PetFrame"] = true,
				["IceHUD_TargetOfTarget"] = true,
				["PartyMemberFrame4"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["Boss4TargetFrame"] = true,
				["PitBull4_Frames_pettarget"] = true,
				["SUFHeaderbossUnitButton2"] = true,
				["PartyMemberFrame2"] = true,
				["PitBull4_Frames_pet"] = true,
				["FocusFrameToT"] = true,
				["TargetFrame"] = true,
				["Boss1TargetFrame"] = true,
				["Boss2TargetFrame"] = true,
				["PartyMemberFrame1"] = true,
				["SUFUnitfocus"] = true,
				["PitBull4_Frames_target"] = true,
				["SUFUnittargettarget"] = true,
				["PitBull4_Frames_focus"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["SUFHeaderbossUnitButton4"] = true,
				["PitBull4_Frames_targettarget"] = true,
				["SUFUnitpet"] = true,
				["SUFUnitplayer"] = true,
				["TargetofTargetFrame"] = true,
			},
		},
		["Xanaomi - Hellscream"] = {
		},
		["Yttrium - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Healing Wave",
						["texture"] = "Interface\\Icons\\Spell_Nature_MagicImmunity",
					},
				},
			},
			["blacklist"] = {
				["PartyMemberFrame2"] = true,
				["TargetFrame"] = true,
				["IceHUD_TargetInfo"] = true,
				["PartyMemberFrame1"] = true,
				["PitBullUnitFrame2"] = true,
				["IceHUD_PlayerInfo"] = true,
				["TargetofTargetFrame"] = true,
				["PitBullUnitFrame4"] = true,
				["PitBullUnitFrame6"] = true,
				["PitBullUnitFrame1"] = true,
				["PetFrame"] = true,
				["IceHUD_TargetOfTarget"] = true,
				["PartyMemberFrame4"] = true,
				["PitBullUnitFrame3"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PitBullUnitFrame5"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["PartyMemberFrame3"] = true,
				["PitBullCluster2UnitButton1"] = true,
				["PitBullCluster1UnitButton1"] = true,
			},
		},
		["Tamori - ChaosWoW Funserver"] = {
		},
		["Bairra - Alterac valley (PVP - INSTA 70)"] = {
		},
		["Knas - Auchindoun"] = {
			["clicksets"] = {
				["Default"] = {
					["Shift-2"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Holy Light",
						["texture"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
					},
					["2"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 2,
						["delete"] = true,
						["arg1"] = "Flash of Light",
						["texture"] = "Interface\\Icons\\Spell_Holy_FlashHeal",
					},
					["3"] = {
						["type"] = "spell",
						["modifier"] = "",
						["button"] = 3,
						["arg1"] = "Cleanse",
						["texture"] = "Interface\\Icons\\Spell_Holy_Renew",
					},
					["Shift-1"] = {
						["type"] = "spell",
						["modifier"] = "Shift-",
						["button"] = 1,
						["arg1"] = "Holy Shock",
						["texture"] = "Interface\\Icons\\Spell_Holy_SearingLight",
					},
				},
			},
			["blacklist"] = {
				["PartyMemberFrame2"] = true,
				["TargetofTargetFrame"] = true,
				["PitBullCluster2UnitButton3"] = true,
				["PitBullCluster2UnitButton4"] = true,
				["PitBullUnitFrame4"] = true,
				["TargetFrame"] = true,
				["IceHUD_TargetInfo"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame1"] = true,
				["PitBullUnitFrame2"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["PartyMemberFrame3"] = true,
				["PitBullUnitFrame1"] = true,
				["PetFrame"] = true,
				["PitBullUnitFrame3"] = true,
				["PitBullCluster1UnitButton4"] = true,
				["PitBullCluster2UnitButton2"] = true,
				["IceHUD_TargetOfTarget"] = true,
				["PartyMemberFrame4"] = true,
				["PitBullCluster1UnitButton2"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["PitBullUnitFrame6"] = true,
				["PitBullUnitFrame5"] = true,
				["PitBullUnitFrame7"] = true,
				["PitBullCluster1UnitButton3"] = true,
				["IceHUD_PlayerClickFrame"] = true,
				["PitBullCluster2UnitButton1"] = true,
				["PitBullCluster1UnitButton1"] = true,
			},
		},
		["Pandohra - Auchindoun"] = {
		},
	},
}
CliqueDB3 = {
	["char"] = {
		["Pooshield - Arthas"] = {
			["alerthidden"] = true,
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnittargettarget"] = true,
				["SUFHeaderbossUnitButton3"] = true,
				["SUFHeadermaintankUnitButton1"] = true,
				["SUFUnitplayer"] = true,
				["SUFUnitfocus"] = true,
				["SUFHeaderbossUnitButton4"] = true,
				["SUFHeaderbossUnitButton2"] = true,
				["SUFUnitfocustarget"] = true,
				["SUFHeaderbossUnitButton1"] = true,
				["SUFUnitpet"] = true,
			},
		},
		["Oxshield - Auchindoun"] = {
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnitfocus"] = true,
				["SUFUnitplayer"] = true,
				["SUFHeadermaintankUnitButton1"] = true,
				["SUFUnitfocustarget"] = true,
				["SUFUnittargettarget"] = true,
				["SUFUnitpet"] = true,
			},
			["alerthidden"] = true,
		},
		["Promitto - Auchindoun"] = {
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnitfocustarget"] = true,
				["CompactPartyFrameMember4Buff1"] = true,
				["CompactPartyFrameMember3Buff3"] = true,
				["CompactPartyFrameMember5"] = true,
				["CompactPartyFrameMember2Debuff3"] = true,
				["TargetFrameToT"] = true,
				["CompactPartyFrameMember5Debuff3"] = true,
				["FocusFrame"] = true,
				["CompactPartyFrameMember5Buff2"] = true,
				["CompactPartyFrameMember1Debuff2"] = true,
				["CompactPartyFrameMember4Buff3"] = true,
				["CompactPartyFrameMember2"] = true,
				["CompactPartyFrameMember5Debuff2"] = true,
				["PartyMemberFrame3"] = true,
				["PetFrame"] = true,
				["SUFHeadermaintankUnitButton1"] = true,
				["PartyMemberFrame4"] = true,
				["Boss3TargetFrame"] = true,
				["PlayerFrame"] = true,
				["PartyMemberFrame3PetFrame"] = true,
				["CompactPartyFrameMember3Debuff3"] = true,
				["CompactPartyFrameMember1Buff3"] = true,
				["PartyMemberFrame2PetFrame"] = true,
				["PartyMemberFrame4PetFrame"] = true,
				["CompactPartyFrameMember4Debuff2"] = true,
				["Boss4TargetFrame"] = true,
				["CompactPartyFrameMember2Debuff1"] = true,
				["CompactPartyFrameMember2Buff1"] = true,
				["SUFUnittargettarget"] = true,
				["PartyMemberFrame2"] = true,
				["CompactPartyFrameMember3Buff1"] = true,
				["SUFUnitpet"] = true,
				["FocusFrameToT"] = true,
				["CompactPartyFrameMember1"] = true,
				["TargetFrame"] = true,
				["Boss1TargetFrame"] = true,
				["Boss2TargetFrame"] = true,
				["CompactPartyFrameMember3Buff2"] = true,
				["PartyMemberFrame1"] = true,
				["CompactPartyFrameMember2Debuff2"] = true,
				["CompactPartyFrameMember1Debuff1"] = true,
				["CompactPartyFrameMember2Buff3"] = true,
				["CompactPartyFrameMember1Debuff3"] = true,
				["CompactPartyFrameMember4"] = true,
				["SUFUnitfocus"] = true,
				["CompactPartyFrameMember5Buff3"] = true,
				["CompactPartyFrameMember1Buff2"] = true,
				["CompactPartyFrameMember5Buff1"] = true,
				["CompactPartyFrameMember4Debuff1"] = true,
				["CompactPartyFrameMember3"] = true,
				["CompactPartyFrameMember3Debuff1"] = true,
				["CompactPartyFrameMember1Buff1"] = true,
				["CompactPartyFrameMember5Debuff1"] = true,
				["PartyMemberFrame1PetFrame"] = true,
				["CompactPartyFrameMember2Buff2"] = true,
				["SUFUnitplayer"] = true,
				["CompactPartyFrameMember4Buff2"] = true,
				["CompactPartyFrameMember4Debuff3"] = true,
				["CompactPartyFrameMember3Debuff2"] = true,
			},
			["alerthidden"] = true,
		},
		["Aset - Auchindoun"] = {
			["alerthidden"] = true,
			["sec_profileKey"] = "Aset - Auchindoun",
			["pri_profileKey"] = "Aset - Auchindoun",
			["fastooc"] = false,
			["downclick"] = false,
			["specswap"] = false,
			["blacklist"] = {
				["SUFUnitplayer"] = true,
				["SUFUnitfocus"] = true,
				["SUFUnittarget"] = true,
				["SUFHeadermaintankUnitButton1"] = true,
				["SUFUnitfocustarget"] = true,
				["SUFUnittargettarget"] = true,
				["SUFUnitpet"] = true,
			},
		},
		["Pooshield - Thrall"] = {
			["alerthidden"] = true,
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFHeaderbossUnitButton2"] = true,
				["SUFHeaderbossUnitButton3"] = true,
				["SUFHeadermaintankUnitButton1"] = true,
				["SUFUnitplayer"] = true,
				["SUFUnitpet"] = true,
				["SUFUnitfocustarget"] = true,
				["SUFHeaderbossUnitButton4"] = true,
				["SUFUnitfocus"] = true,
				["SUFUnittargettarget"] = true,
				["SUFHeaderbossUnitButton1"] = true,
				["SUFHeadermaintankUnitButton2"] = true,
			},
		},
		["Chukk - Auchindoun"] = {
			["alerthidden"] = true,
			["sec_profileKey"] = "Chukk - Auchindoun",
			["pri_profileKey"] = "Chukk - Auchindoun",
			["fastooc"] = false,
			["downclick"] = false,
			["specswap"] = false,
			["blacklist"] = {
				["SUFUnittarget"] = true,
				["SUFUnitfocus"] = true,
				["SUFHeadermaintankUnitButton1"] = true,
				["TargetFrame"] = true,
				["SUFUnitplayer"] = true,
				["Boss2TargetFrame"] = true,
				["Boss3TargetFrame"] = true,
				["Boss1TargetFrame"] = true,
				["SUFUnitfocustarget"] = true,
				["SUFUnittargettarget"] = true,
				["Boss4TargetFrame"] = true,
				["SUFUnitpet"] = true,
			},
		},
	},
	["profileKeys"] = {
		["Kernelpanic - Auchindoun"] = "Kernelpanic - Auchindoun",
		["Oxshield - Auchindoun"] = "Oxshield - Auchindoun",
		["Chukk - Auchindoun"] = "Chukk - Auchindoun",
		["Gacrux - Auchindoun"] = "Gacrux - Auchindoun",
		["Pooshield - Arthas"] = "Pooshield - Arthas",
		["Itsashaman - Arthas"] = "Itsashaman - Arthas",
		["Aset - Auchindoun"] = "Aset - Auchindoun",
		["Pooshield - Thrall"] = "Pooshield - Thrall",
		["Promitto - Auchindoun"] = "Promitto - Auchindoun",
		["Aonah - Auchindoun"] = "Aonah - Auchindoun",
	},
	["profiles"] = {
		["Kernelpanic - Auchindoun"] = {
			["bindings"] = {
				{
					["type"] = "target",
					["sets"] = {
						["default"] = true,
					},
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["type"] = "menu",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
				}, -- [2]
			},
		},
		["Oxshield - Auchindoun"] = {
			["bindings"] = {
				{
					["type"] = "target",
					["sets"] = {
						["default"] = true,
					},
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["spell"] = "Word of Glory",
					["key"] = "BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "INTERFACE\\ICONS\\inv_helmet_96",
					["type"] = "spell",
				}, -- [2]
				{
					["spell"] = "Flash of Light",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_FlashHeal",
					["type"] = "spell",
				}, -- [3]
				{
					["spell"] = "Holy Light",
					["key"] = "SHIFT-BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
					["type"] = "spell",
				}, -- [4]
			},
		},
		["Chukk - Auchindoun"] = {
			["bindings"] = {
				{
					["sets"] = {
						["default"] = true,
					},
					["type"] = "target",
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["spell"] = "Dispel Magic",
					["key"] = "BUTTON5",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_DispelMagic",
					["type"] = "spell",
				}, -- [2]
				{
					["spell"] = "Renew",
					["key"] = "BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_Renew",
					["type"] = "spell",
				}, -- [3]
				{
					["spell"] = "Power Word: Shield",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_PowerWordShield",
					["type"] = "spell",
				}, -- [4]
				{
					["spell"] = "Prayer of Mending",
					["key"] = "SHIFT-BUTTON1",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_PrayerOfMendingtga",
					["type"] = "spell",
				}, -- [5]
				{
					["spell"] = "Leap of Faith",
					["key"] = "SHIFT-BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "INTERFACE\\ICONS\\priest_spell_leapoffaith_a",
					["type"] = "spell",
				}, -- [6]
				{
					["spell"] = "Circle of Healing",
					["key"] = "SHIFT-BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_CircleOfRenewal",
					["type"] = "spell",
				}, -- [7]
				{
					["spell"] = "Cure Disease",
					["key"] = "BUTTON4",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_NullifyDisease",
					["type"] = "spell",
				}, -- [8]
				{
					["spell"] = "Leap of Faith",
					["key"] = "CTRL-BUTTON1",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "INTERFACE\\ICONS\\priest_spell_leapoffaith_a",
					["type"] = "spell",
				}, -- [9]
			},
		},
		["Gacrux - Auchindoun"] = {
			["bindings"] = {
				{
					["type"] = "target",
					["sets"] = {
						["default"] = true,
					},
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["type"] = "menu",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
				}, -- [2]
			},
		},
		["Pooshield - Arthas"] = {
			["bindings"] = {
				{
					["sets"] = {
						["default"] = true,
					},
					["type"] = "target",
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["spell"] = "Chain Heal",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Nature_HealingWaveGreater",
					["type"] = "spell",
				}, -- [2]
				{
					["spell"] = "Earth Shield",
					["key"] = "BUTTON4",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Nature_SkinofEarth",
					["type"] = "spell",
				}, -- [3]
				{
					["spell"] = "Healing Surge",
					["key"] = "SHIFT-BUTTON1",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Nature_HealingWay",
					["type"] = "spell",
				}, -- [4]
				{
					["spell"] = "Riptide",
					["key"] = "BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\spell_nature_riptide",
					["type"] = "spell",
				}, -- [5]
				{
					["spell"] = "Healing Wave",
					["key"] = "SHIFT-BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Nature_MagicImmunity",
					["type"] = "spell",
				}, -- [6]
				{
					["spell"] = "Cleanse Spirit",
					["key"] = "BUTTON5",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Ability_Shaman_CleanseSpirit",
					["type"] = "spell",
				}, -- [7]
				{
					["spell"] = "Greater Healing Wave",
					["key"] = "SHIFT-BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Nature_HealingWaveLesser",
					["type"] = "spell",
				}, -- [8]
			},
		},
		["Itsashaman - Arthas"] = {
			["bindings"] = {
				{
					["sets"] = {
						["default"] = true,
					},
					["type"] = "target",
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["type"] = "menu",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
				}, -- [2]
			},
		},
		["Aset - Auchindoun"] = {
			["bindings"] = {
				{
					["type"] = "target",
					["sets"] = {
						["default"] = true,
					},
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["spell"] = "Rejuvenation",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Nature_Rejuvenation",
					["type"] = "spell",
				}, -- [2]
				{
					["spell"] = "Remove Corruption",
					["key"] = "BUTTON5",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_RemoveCurse",
					["type"] = "spell",
				}, -- [3]
				{
					["spell"] = "Lifebloom",
					["key"] = "BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\INV_Misc_Herb_Felblossom",
					["type"] = "spell",
				}, -- [4]
			},
		},
		["Pooshield - Thrall"] = {
			["bindings"] = {
				{
					["sets"] = {
						["default"] = true,
					},
					["type"] = "target",
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["spell"] = "Cleanse Spirit",
					["key"] = "BUTTON5",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Ability_Shaman_CleanseSpirit",
					["type"] = "spell",
				}, -- [2]
				{
					["spell"] = "Earth Shield",
					["key"] = "BUTTON4",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Nature_SkinofEarth",
					["type"] = "spell",
				}, -- [3]
				{
					["spell"] = "Chain Heal",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Nature_HealingWaveGreater",
					["type"] = "spell",
				}, -- [4]
				{
					["spell"] = "Riptide",
					["key"] = "BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\spell_nature_riptide",
					["type"] = "spell",
				}, -- [5]
			},
		},
		["Promitto - Auchindoun"] = {
			["bindings"] = {
				{
					["sets"] = {
						["default"] = true,
					},
					["type"] = "target",
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["spell"] = "Cleanse",
					["key"] = "BUTTON4",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_Purify",
					["type"] = "spell",
				}, -- [2]
				{
					["spell"] = "Cleanse",
					["key"] = "BUTTON5",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_Purify",
					["type"] = "spell",
				}, -- [3]
				{
					["spell"] = "Beacon of Light",
					["key"] = "SHIFT-BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Ability_Paladin_BeaconofLight",
					["type"] = "spell",
				}, -- [4]
				{
					["spell"] = "Holy Shock",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_SearingLight",
					["type"] = "spell",
				}, -- [5]
				{
					["spell"] = "Word of Glory",
					["key"] = "BUTTON3",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "INTERFACE\\ICONS\\inv_helmet_96",
					["type"] = "spell",
				}, -- [6]
				{
					["spell"] = "Holy Light",
					["key"] = "SHIFT-BUTTON2",
					["sets"] = {
						["default"] = true,
					},
					["icon"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
					["type"] = "spell",
				}, -- [7]
			},
		},
		["Aonah - Auchindoun"] = {
			["bindings"] = {
				{
					["sets"] = {
						["default"] = true,
					},
					["type"] = "target",
					["key"] = "BUTTON1",
					["unit"] = "mouseover",
				}, -- [1]
				{
					["type"] = "menu",
					["key"] = "BUTTON2",
					["sets"] = {
						["default"] = true,
					},
				}, -- [2]
			},
		},
	},
}
