
CooldownTimersDB = {
	["classes"] = {
		["Warrior"] = {
			["cooldowns"] = {
				["Battle Stance"] = {
					["id"] = 8,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Warrior_OffensiveStance",
					["start"] = 0,
				},
				["War Stomp"] = {
					["id"] = 7,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_WarStomp",
					["start"] = 0,
				},
			},
		},
		["Paladin"] = {
			["cooldowns"] = {
				["Divine Intervention"] = {
					["id"] = 51,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Nature_TimeStop",
					["group"] = "CDT",
				},
				["Exorcism"] = {
					["id"] = 21,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_Excorcism_02",
					["group"] = "CDT",
				},
				["Mana Tap"] = {
					["id"] = 13,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Arcane_ManaTap",
					["group"] = "CDT",
				},
				["Blessing of Protection"] = {
					["id"] = 46,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_SealOfProtection",
					["group"] = "CDT",
				},
				["Divine Protection"] = {
					["id"] = 52,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_Restoration",
					["group"] = "CDT",
				},
				["Divine Shield"] = {
					["id"] = 54,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_DivineIntervention",
					["group"] = "CDT",
				},
				["Lay on Hands"] = {
					["id"] = 32,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_LayOnHands",
					["group"] = "CDT",
				},
				["Righteous Defense"] = {
					["id"] = 59,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Shoulder_37",
					["group"] = "CDT",
				},
				["Arcane Torrent"] = {
					["id"] = 2,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Shadow_Teleport",
					["group"] = "CDT",
				},
				["Hammer of Justice"] = {
					["id"] = 57,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_SealOfMight",
					["group"] = "CDT",
				},
				["Basic Campfire"] = {
					["id"] = 4,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Fire_Fire",
					["group"] = "CDT",
				},
				["Consecration"] = {
					["id"] = 19,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_InnerFire",
					["group"] = "CDT",
				},
				["Turn Undead"] = {
					["id"] = 44,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_TurnUndead",
					["group"] = "CDT",
				},
				["Blessing of Freedom"] = {
					["id"] = 45,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_SealOfValor",
					["group"] = "CDT",
				},
				["Judgement"] = {
					["id"] = 68,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_RighteousFury",
					["group"] = "CDT",
				},
			},
		},
		["Shaman"] = {
			["cooldowns"] = {
				["Fire Nova Totem"] = {
					["id"] = 17,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Fire_SealOfFire",
					["start"] = 0,
				},
				["Stoneclaw Totem"] = {
					["id"] = 25,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_StoneClawTotem",
					["start"] = 0,
				},
				["Basic Campfire"] = {
					["id"] = 2,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Fire_Fire",
					["start"] = 0,
				},
				["Earthbind Totem"] = {
					["id"] = 16,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02",
					["start"] = 0,
				},
				["Earth Shock"] = {
					["id"] = 13,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_EarthShock",
					["start"] = 0,
				},
				["War Stomp"] = {
					["id"] = 12,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_WarStomp",
					["start"] = 0,
				},
				["Flame Shock"] = {
					["id"] = 18,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Fire_FlameShock",
					["start"] = 0,
				},
			},
		},
		["Rogue"] = {
			["cooldowns"] = {
				["Mana Tap"] = {
					["id"] = 13,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Arcane_ManaTap",
					["start"] = 0,
				},
				["Evasion"] = {
					["id"] = 20,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Shadow_ShadowWard",
					["start"] = 0,
				},
				["Gouge"] = {
					["id"] = 21,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Gouge",
					["start"] = 0,
				},
				["Shoot"] = {
					["id"] = 14,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Marksmanship",
					["start"] = 0,
				},
				["Arcane Torrent"] = {
					["id"] = 2,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Shadow_Teleport",
					["start"] = 0,
				},
				["Basic Campfire"] = {
					["id"] = 4,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Fire_Fire",
					["start"] = 0,
				},
				["Throw"] = {
					["id"] = 16,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Throw",
					["start"] = 0,
				},
				["Stealth"] = {
					["id"] = 26,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Stealth",
					["start"] = 0,
				},
				["Sprint"] = {
					["id"] = 23,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Rogue_Sprint",
					["start"] = 0,
				},
			},
		},
		["Warlock"] = {
			["cooldowns"] = {
				["Mana Tap"] = {
					["start"] = 0,
					["id"] = 6,
					["icon"] = "Interface\\Icons\\Spell_Arcane_ManaTap",
					["group"] = "CDT",
				},
				["Blood Fury"] = {
					["start"] = 1314555.638,
					["id"] = 4,
					["icon"] = "Interface\\Icons\\Racial_Orc_BerserkerStrength",
					["group"] = "CDT",
				},
				["Cannibalize"] = {
					["start"] = 0,
					["id"] = 2,
					["icon"] = "Interface\\Icons\\Ability_Racial_Cannibalize",
					["group"] = "CDT",
				},
				["Shoot"] = {
					["start"] = 1314555.638,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\INV_Staff_02",
					["id"] = 11,
				},
				["Arcane Torrent"] = {
					["start"] = 0,
					["id"] = 2,
					["icon"] = "Interface\\Icons\\Spell_Shadow_Teleport",
					["group"] = "CDT",
				},
				["Basic Campfire"] = {
					["group"] = "CDT",
					["start"] = 1314555.638,
					["icon"] = "Interface\\Icons\\Spell_Fire_Fire",
					["id"] = 3,
				},
				["Will of the Forsaken"] = {
					["start"] = 0,
					["id"] = 7,
					["icon"] = "Interface\\Icons\\Spell_Shadow_RaiseDead",
					["group"] = "CDT",
				},
			},
		},
		["Priest"] = {
			["cooldowns"] = {
				["Will of the Forsaken"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Shadow_RaiseDead",
					["id"] = 15,
				},
				["Inner Focus"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Frost_WindWalkOn",
					["id"] = 31,
				},
				["Cannibalize"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Ability_Racial_Cannibalize",
					["id"] = 3,
				},
				["Prayer of Mending"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_PrayerOfMendingtga",
					["id"] = 115,
				},
				["Mind Blast"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Shadow_UnholyFrenzy",
					["id"] = 158,
				},
				["Shadow Word: Death"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Shadow_DemonicFortitude",
					["id"] = 187,
				},
				["Shoot"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Wand_23",
					["id"] = 12,
				},
				["Devouring Plague"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Shadow_BlackPlague",
					["id"] = 144,
				},
				["Power Word: Shield"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_PowerWordShield",
					["id"] = 48,
				},
				["Basic Campfire"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Fire_Fire",
					["id"] = 2,
				},
				["Shadowfiend"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Shadow_Shadowfiend",
					["id"] = 199,
				},
				["Fade"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Magic_LesserInvisibilty",
					["id"] = 151,
				},
				["Fear Ward"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Holy_Excorcism",
					["id"] = 23,
				},
				["Psychic Scream"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Shadow_PsychicScream",
					["id"] = 179,
				},
			},
		},
		["Hunter"] = {
			["cooldowns"] = {
				["Disengage"] = {
					["group"] = "CDT",
					["id"] = 45,
					["icon"] = "Interface\\Icons\\Ability_Rogue_Feint",
					["start"] = 0,
				},
				["Raptor Strike"] = {
					["group"] = "CDT",
					["id"] = 35,
					["icon"] = "Interface\\Icons\\Ability_MeleeDamage",
					["start"] = 0,
				},
				["Concussive Shot"] = {
					["group"] = "CDT",
					["id"] = 28,
					["icon"] = "Interface\\Icons\\Spell_Frost_Stun",
					["start"] = 1190798.991,
				},
				["Immolation Trap"] = {
					["group"] = "CDT",
					["id"] = 33,
					["icon"] = "Interface\\Icons\\Spell_Fire_FlameShock",
					["start"] = 0,
				},
				["Distracting Shot"] = {
					["group"] = "CDT",
					["id"] = 29,
					["icon"] = "Interface\\Icons\\Spell_Arcane_Blink",
					["start"] = 1190796.672,
				},
				["Arcane Shot"] = {
					["group"] = "CDT",
					["id"] = 25,
					["icon"] = "Interface\\Icons\\Ability_ImpalingBolt",
					["start"] = 1190793.354,
				},
				["Throw"] = {
					["group"] = "CDT",
					["id"] = 14,
					["icon"] = "Interface\\Icons\\Ability_Throw",
					["start"] = 0,
				},
				["Auto Shot"] = {
					["group"] = "CDT",
					["id"] = 27,
					["icon"] = "Interface\\Icons\\INV_Weapon_Bow_06",
					["start"] = 0,
				},
				["Berserking"] = {
					["group"] = "CDT",
					["id"] = 4,
					["icon"] = "Interface\\Icons\\Racial_Troll_Berserk",
					["start"] = 0,
				},
				["Scare Beast"] = {
					["group"] = "CDT",
					["id"] = 23,
					["icon"] = "Interface\\Icons\\Ability_Druid_Cower",
					["start"] = 0,
				},
				["Mongoose Bite"] = {
					["group"] = "CDT",
					["id"] = 34,
					["icon"] = "Interface\\Icons\\Ability_Hunter_SwiftStrike",
					["start"] = 0,
				},
				["Freezing Trap"] = {
					["group"] = "CDT",
					["id"] = 46,
					["icon"] = "Interface\\Icons\\Spell_Frost_ChainsOfIce",
					["start"] = 0,
				},
				["Multi-Shot"] = {
					["group"] = "CDT",
					["id"] = 40,
					["icon"] = "Interface\\Icons\\Ability_UpgradeMoonGlaive",
					["start"] = 0,
				},
			},
		},
		["Druid"] = {
			["cooldowns"] = {
				["Enrage"] = {
					["id"] = 96,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Druid_Enrage",
					["start"] = 0,
				},
				["Prowl"] = {
					["id"] = 105,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Ambush",
					["start"] = 0,
				},
				["Tranquility"] = {
					["id"] = 174,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_Tranquility",
					["start"] = 0,
				},
				["Hurricane"] = {
					["id"] = 33,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_Cyclone",
					["start"] = 0,
				},
				["Feral Charge"] = {
					["id"] = 96,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Hunter_Pet_Bear",
					["start"] = 0,
				},
				["Growl"] = {
					["id"] = 100,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Physical_Taunt",
					["start"] = 0,
				},
				["Swiftmend"] = {
					["id"] = 173,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Relics_IdolofRejuvenation",
					["group"] = "CDT",
				},
				["Faerie Fire (Feral)"] = {
					["id"] = 90,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_FaerieFire",
					["start"] = 0,
				},
				["Mangle (Bear)"] = {
					["id"] = 96,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Druid_Mangle2",
					["start"] = 0,
				},
				["Frenzied Regeneration"] = {
					["id"] = 99,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_BullRush",
					["start"] = 0,
				},
				["Force of Nature"] = {
					["id"] = 30,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Ability_Druid_ForceofNature",
					["group"] = "CDT",
				},
				["Maim"] = {
					["id"] = 102,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Druid_Mangle.tga",
					["start"] = 0,
				},
				["Bash"] = {
					["id"] = 88,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Druid_Bash",
					["start"] = 0,
				},
				["Tiger's Fury"] = {
					["id"] = 112,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Mount_JungleTiger",
					["start"] = 0,
				},
				["Nature's Grasp"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Nature_NaturesWrath",
					["id"] = 50,
				},
				["Rebirth"] = {
					["id"] = 143,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_Reincarnation",
					["start"] = 0,
				},
				["Barkskin"] = {
					["id"] = 16,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_StoneClawTotem",
					["start"] = 0,
				},
				["Cower"] = {
					["id"] = 92,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Druid_Cower",
					["start"] = 0,
				},
				["Challenging Roar"] = {
					["id"] = 90,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Druid_ChallangingRoar",
					["start"] = 0,
				},
				["Basic Campfire"] = {
					["id"] = 3,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Fire_Fire",
					["start"] = 0,
				},
				["Dash"] = {
					["id"] = 93,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_Druid_Dash",
					["start"] = 0,
				},
				["Innervate"] = {
					["id"] = 37,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Spell_Nature_Lightning",
					["start"] = 0,
				},
				["War Stomp"] = {
					["id"] = 15,
					["group"] = "CDT",
					["icon"] = "Interface\\Icons\\Ability_WarStomp",
					["start"] = 0,
				},
				["Nature's Swiftness"] = {
					["group"] = "CDT",
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Spell_Nature_RavenForm",
					["id"] = 142,
				},
			},
		},
	},
	["profiles"] = {
		["Default"] = {
			["detachedTooltip"] = {
			},
			["pulse"] = {
				["loc"] = {
					["y"] = 110.8566360473633,
					["x"] = -16.00010108947754,
				},
				["locked"] = true,
				["size"] = 141.1436157226563,
			},
			["showIcon"] = true,
			["groups"] = {
				["GroupCooldowns"] = {
					["y"] = 220.5716857910156,
					["x"] = 345.1431579589844,
					["point"] = "LEFT",
					["locked"] = true,
					["relPoint"] = "LEFT",
				},
				["CDT"] = {
					["y"] = 31.99979782104492,
					["x"] = 59.4285774230957,
					["point"] = "LEFT",
					["locked"] = true,
					["relPoint"] = "LEFT",
				},
				["PetCooldowns"] = {
					["y"] = 131.4286499023438,
					["x"] = 316.5714416503906,
					["point"] = "LEFT",
					["locked"] = true,
					["relPoint"] = "LEFT",
				},
				["ItemCooldowns"] = {
					["y"] = -113.1425552368164,
					["x"] = 52.57159805297852,
					["point"] = "LEFT",
					["locked"] = true,
					["relPoint"] = "LEFT",
				},
			},
			["barOptions"] = {
				["barwidth"] = 198,
			},
			["announce"] = {
				["y"] = 235.428466796875,
				["locked"] = true,
				["x"] = 6.747709267074242e-005,
			},
			["itemcooldowns"] = {
				["Dark Iron Smoking Pipe"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Misc_Pipe_01",
					["start"] = 0,
				},
				["Goldenmist Special Brew"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_10",
					["group"] = "ItemCooldowns",
				},
				["Elixir of Major Fortitude"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_158",
					["start"] = 0,
				},
				["Lesser Healing Potion"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_50",
					["start"] = 0,
				},
				["Imbued Silver Spear"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Spear_04",
					["group"] = "ItemCooldowns",
				},
				["Swim Speed Potion"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_13",
					["group"] = "ItemCooldowns",
				},
				["Horn of Echeyakee"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Horn_01",
					["group"] = "ItemCooldowns",
				},
				["Antheol's Disciplinary Rod"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Staff_10",
					["group"] = "ItemCooldowns",
				},
				["Ancient Draenei War Talisman"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Jewelry_Talisman_14",
					["start"] = 0,
				},
				["Elixir of Major Agility"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_127",
					["start"] = 0,
				},
				["Blazing Torch"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Torch_Lit",
					["group"] = "ItemCooldowns",
				},
				["Minor Healthstone"] = {
					["disabled"] = false,
					["start"] = 1313753.071,
					["icon"] = "Interface\\Icons\\INV_Stone_04",
					["group"] = "ItemCooldowns",
				},
				["Unstable Flask of the Beast"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_35",
					["start"] = 0,
				},
				["Direbrew's Remote"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Gizmo_GoblingTonkController",
					["start"] = 0,
				},
				["Cracked Power Core"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Gem_Diamond_02",
					["group"] = "ItemCooldowns",
				},
				["Major Rejuvenation Potion"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_47",
					["start"] = 0,
				},
				["Bangle of Endless Blessings"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Jewelry_Necklace_27",
					["group"] = "ItemCooldowns",
				},
				["Bottled Nethergon Vapor"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_153",
					["start"] = 0,
				},
				["Great White Kodo"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\Ability_Mount_Kodo_01",
					["start"] = 0,
				},
				["Horn of the Swift Timber Wolf"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
					["group"] = "ItemCooldowns",
				},
				["Condensed Mana Powder"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Misc_Gem_Sapphire_03",
					["start"] = 0,
				},
				["Mad Alchemist's Potion"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_28",
					["group"] = "ItemCooldowns",
				},
				["Elixir of Draenic Wisdom"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_155",
					["start"] = 0,
				},
				["Multiphase Spectrographic Goggles"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Gizmo_NewGoggles",
					["start"] = 0,
				},
				["Darnarian's Scroll of Teleportation"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Scroll_02",
					["group"] = "ItemCooldowns",
				},
				["Direbrew Hops"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Herb_08",
					["group"] = "ItemCooldowns",
				},
				["Bottled Nethergon Energy"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_156",
					["start"] = 0,
				},
				["Ice Cold Milk"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Drink_Milk_01",
					["group"] = "ItemCooldowns",
				},
				["Banishing Crystal"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Misc_Gem_AzureDraenite_02",
					["start"] = 0,
				},
				["Balebrew Charm"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Drink_04",
					["group"] = "ItemCooldowns",
				},
				["Ancient Crystal Talisman"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Jewelry_Necklace_28",
					["start"] = 0,
				},
				["Attuned Crystal Cores"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Misc_Gem_Variety_02",
					["start"] = 0,
				},
				["Terokkar Tablet of Precision"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Misc_StoneTablet_11",
					["start"] = 0,
				},
				["Super Mana Potion"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_137",
					["group"] = "ItemCooldowns",
				},
				["Black Hawkstrider"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Ability_Mount_CockatriceMount_Black",
					["group"] = "ItemCooldowns",
				},
				["Elixir of Ironskin"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_159",
					["start"] = 0,
				},
				["Minor Mana Potion"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_70",
					["group"] = "ItemCooldowns",
				},
				["Minor Healing Potion"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_49",
					["group"] = "ItemCooldowns",
				},
				["Hearthstone"] = {
					["disabled"] = false,
					["start"] = 1314797.394,
					["icon"] = "Interface\\Icons\\INV_Misc_Rune_01",
					["group"] = "ItemCooldowns",
				},
				["Minor Soulstone"] = {
					["group"] = "ItemCooldowns",
					["start"] = 1315052.299,
					["icon"] = "Interface\\Icons\\INV_Misc_Orb_04",
					["disabled"] = false,
				},
				["Super Healing Potion"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_131",
					["start"] = 0,
				},
				["Elixir of Major Defense"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_122",
					["group"] = "ItemCooldowns",
				},
				["Refreshing Spring Water"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Drink_07",
					["group"] = "ItemCooldowns",
				},
				["Vim'gol's Grimoire"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Misc_Book_06",
					["start"] = 0,
				},
				["Blue Ogre Brew Special"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_73",
					["group"] = "ItemCooldowns",
				},
				["Linen Bandage"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Bandage_15",
					["group"] = "ItemCooldowns",
				},
				["Ruby Slippers"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Boots_Cloth_09",
					["start"] = 0,
				},
				["Bloodberry Elixir"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_111",
					["start"] = 0,
				},
				["Purple Skeletal Warhorse"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Ability_Mount_Undeadhorse",
					["group"] = "ItemCooldowns",
				},
				["Red Ogre Brew Special"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_52",
					["group"] = "ItemCooldowns",
				},
				["Elixir of Mastery"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_111",
					["start"] = 0,
				},
				["Swift Purple Windrider"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\Ability_Mount_Wyvern_01",
					["start"] = 0,
				},
				["Skyguard Blasting Charges"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Bomb_07",
					["group"] = "ItemCooldowns",
				},
				["Master Healthstone"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Stone_04",
					["group"] = "ItemCooldowns",
				},
				["Infused Crystal"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Gem_Diamond_02",
					["group"] = "ItemCooldowns",
				},
				["Skyguard Bombs"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Bomb_04",
					["group"] = "ItemCooldowns",
				},
				["Foreman's Blackjack"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Mace_11",
					["start"] = 0,
				},
				["Horn of the Frostwolf Howler"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Horn_01",
					["group"] = "ItemCooldowns",
				},
				["Crystalized Mana Residue"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Gem_Sapphire_03",
					["group"] = "ItemCooldowns",
				},
				["Major Healing Potion"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Potion_54",
					["group"] = "ItemCooldowns",
				},
				["Frostwolf Insignia Rank 3"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Jewelry_FrostwolfTrinket_02",
					["start"] = 0,
				},
				["Empty Mug of Direbrew"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Drink_03",
					["group"] = "ItemCooldowns",
				},
				["Shattered Sun Banner"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_BRD_Banner",
					["start"] = 0,
				},
				["Fel Siphon"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Qiraj_JewelEngraved",
					["start"] = 0,
				},
				["Silver Dragonhawk Hatchling"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Ability_Hunter_Pet_DragonHawk",
					["group"] = "ItemCooldowns",
				},
				["Adamantine Figurine"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_QirajIdol_Sage",
					["start"] = 0,
				},
				["Red-speckled Mushroom"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Mushroom_11",
					["group"] = "ItemCooldowns",
				},
				["Green Windrider"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\Ability_Mount_Wyvern_01",
					["group"] = "ItemCooldowns",
				},
				["Glyphs of Summoning"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Rune_03",
					["group"] = "ItemCooldowns",
				},
				["Elixir of Shadow Power"] = {
					["disabled"] = false,
					["group"] = "ItemCooldowns",
					["icon"] = "Interface\\Icons\\INV_Potion_46",
					["start"] = 0,
				},
				["Icon of Unyielding Courage"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_BRD_Banner",
					["group"] = "ItemCooldowns",
				},
				["Tough Hunk of Bread"] = {
					["disabled"] = false,
					["start"] = 0,
					["icon"] = "Interface\\Icons\\INV_Misc_Food_11",
					["group"] = "ItemCooldowns",
				},
			},
		},
	},
}
