
CT_CoreOptions = {
	["CHAR-Zik-Zuluhed"] = {
		["questTrackerAnchor"] = false,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["minimapIcon"] = 1,
		["guildNotes"] = {
		},
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Lliliillili"] = "will buy spellcloth cd",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Jadow"] = "killed big guy in Nagrand",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Gorefist"] = "will tank again (durnholde)",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Antiok"] = "has riding speed enchant!",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "no longer enchanter",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Limmdul"] = "375 JC !gems",
			["Nocowlvl"] = "Welshman",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Pickpocket"] = "Karen",
		},
		["castingTimers"] = false,
		["minimapY"] = 712.76171875,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tickMod"] = false,
		["minimapX"] = 1214.766235351563,
		["tooltipRelocationAnchor"] = false,
		["questTracker"] = 1,
		["hideWorldMap"] = 1,
	},
	["CHAR-Aonarap-Hellscream"] = {
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Furybringer"] = "Another pally we helped in STV",
			["Acani"] = "helped me",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Kanoka"] = "ruan sm",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Frostarical"] = "wants me to join guild soon",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Aljezzar"] = "ran SM",
			["Ani"] = "Kristine",
			["Deathpsalm"] = "ran SM with him/her",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Azzman"] = "ran sm",
			["Ardurren"] = "Matt",
			["Matsica"] = "ra uldaman",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Cudly"] = "played SM with him",
			["Bigflamer"] = "ran sm has raid guild",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Antiok"] = "has riding speed enchant!",
			["Linaril"] = "ran uldaman",
			["Targu"] = "Jeffery",
			["Floranu"] = "ran sm",
			["Darkmaggic"] = "did sm",
			["Mithrindell"] = "ran sm with him",
			["Jujusen"] = "ran zf, good priest",
		},
		["guildNotes"] = {
		},
	},
	["CHAR-Aonarah-Hellscream"] = {
		["friendNotes"] = {
			["Greenglass"] = "gave free port to TB!",
			["Ani"] = "Kristine",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Acani"] = "helped me",
			["Alandren"] = "Joe",
			["Kaerin"] = "Karen, duh",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Frostarical"] = "wants me to join guild soon",
			["Averin"] = "Joe's Alt",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Nyum"] = "healed on RFK run",
			["Arolan"] = "Steve",
			["Antiok"] = "has riding speed enchant!",
			["Furybringer"] = "Another pally we helped in STV",
			["Tjthepally"] = "pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Ardurren"] = "Matt",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Varegirne"] = "Kris Durid",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
		},
		["guildNotes"] = {
		},
	},
	["CHAR-Japhaar-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["guildNotes"] = {
		},
		["hideGryphons"] = false,
		["tooltipRelocation"] = 1,
		["questTracker"] = 1,
		["minimapIcon"] = 1,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Sadjah"] = "Erin",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Antiok"] = "has riding speed enchant!",
			["Jadow"] = "killed big guy in Nagrand",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Ardurren"] = "Matt",
		},
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tooltipRelocationAnchor"] = false,
		["tickMod"] = false,
		["castingTimers"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Anokank-Hellscream"] = {
		["friendNotes"] = {
			["Mejah"] = "Erin",
			["Jyll"] = "Karen",
		},
	},
	["CHAR-Tolate-Hellscream"] = {
		["minimapIcon"] = 1,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["guildNotes"] = {
		},
		["castingTimers"] = false,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Lliliillili"] = "will buy spellcloth cd",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Jadow"] = "killed big guy in Nagrand",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Gorefist"] = "will tank again (durnholde)",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Antiok"] = "has riding speed enchant!",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "no longer enchanter",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Limmdul"] = "375 JC !gems",
			["Nocowlvl"] = "Welshman",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Pickpocket"] = "Karen",
		},
		["tooltipRelocationAnchor"] = false,
		["minimapY"] = 712.76171875,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tickMod"] = false,
		["minimapX"] = 1214.766235351563,
		["questTracker"] = 1,
		["questTrackerAnchor"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Prudey-Laughing Skull"] = {
		["friendNotes"] = {
			["Sanguina"] = "Rob",
		},
	},
	["CHAR-Abeninka-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["guildNotes"] = {
		},
		["hideGryphons"] = false,
		["tooltipRelocation"] = 1,
		["questTracker"] = 1,
		["minimapIcon"] = 1,
		["friendNotes"] = {
			["Ani"] = "Kristine",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Acani"] = "helped me",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Alandren"] = "Joe",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Nyum"] = "healed on RFK run",
			["Sadjah"] = "Erin",
			["Ardurren"] = "Matt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Furybringer"] = "Another pally we helped in STV",
			["Arolan"] = "Steve",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Antiok"] = "has riding speed enchant!",
			["Tjthepally"] = "pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Averin"] = "Joe's Alt",
			["Leetfade"] = "sold me Core of Earth",
			["Frostarical"] = "wants me to join guild soon",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
		},
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tooltipRelocationAnchor"] = false,
		["tickMod"] = false,
		["castingTimers"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Rimbaa-Hellscream"] = {
		["friendNotes"] = {
			["Ani"] = "Kristine",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Acani"] = "helped me",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Frostarical"] = "wants me to join guild soon",
			["Averin"] = "Joe's Alt",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Antiok"] = "has riding speed enchant!",
			["Arolan"] = "Steve",
			["Nyum"] = "healed on RFK run",
			["Furybringer"] = "Another pally we helped in STV",
			["Tjthepally"] = "pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Ardurren"] = "Matt",
			["Alandren"] = "Joe",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
		},
		["guildNotes"] = {
		},
	},
	["CHAR-Dolivis-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["guildNotes"] = {
		},
		["hideGryphons"] = false,
		["tooltipRelocation"] = 1,
		["questTracker"] = 1,
		["minimapIcon"] = 1,
		["friendNotes"] = {
			["Ani"] = "Kristine",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Acani"] = "helped me",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Frostarical"] = "wants me to join guild soon",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Averin"] = "Joe's Alt",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Ardurren"] = "Matt",
			["Sadjah"] = "Erin",
			["Nyum"] = "healed on RFK run",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Antiok"] = "has riding speed enchant!",
			["Arolan"] = "Steve",
			["Furybringer"] = "Another pally we helped in STV",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Tjthepally"] = "pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Leetfade"] = "sold me Core of Earth",
			["Alandren"] = "Joe",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
		},
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tooltipRelocationAnchor"] = false,
		["tickMod"] = false,
		["castingTimers"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Krisgurl-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["guildNotes"] = {
		},
		["hideGryphons"] = false,
		["tooltipRelocation"] = 1,
		["questTracker"] = 1,
		["minimapIcon"] = 1,
		["friendNotes"] = {
			["Ani"] = "Kristine",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Acani"] = "helped me",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Alandren"] = "Joe",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Nyum"] = "healed on RFK run",
			["Sadjah"] = "Erin",
			["Ardurren"] = "Matt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Furybringer"] = "Another pally we helped in STV",
			["Arolan"] = "Steve",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Antiok"] = "has riding speed enchant!",
			["Tjthepally"] = "pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Averin"] = "Joe's Alt",
			["Leetfade"] = "sold me Core of Earth",
			["Frostarical"] = "wants me to join guild soon",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
		},
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tooltipRelocationAnchor"] = false,
		["tickMod"] = false,
		["castingTimers"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Thunderdome-Laughing Skull"] = {
		["questTrackerAnchor"] = false,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["guildNotes"] = {
		},
		["minimapIcon"] = 1,
		["questTracker"] = 1,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Jadow"] = "killed big guy in Nagrand",
			["Antiok"] = "has riding speed enchant!",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Ardurren"] = "Matt",
			["Gorefist"] = "will tank again (durnholde)",
		},
		["minimapX"] = 1214.766235351563,
		["tickMod"] = false,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["minimapY"] = 712.76171875,
		["castingTimers"] = false,
		["tooltipRelocationAnchor"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Nohsk-Hellscream"] = {
		["minimapIcon"] = 1,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["questTrackerAnchor"] = false,
		["questTracker"] = 1,
		["castingTimers"] = false,
		["tooltipRelocationAnchor"] = false,
		["minimapX"] = 1214.766235351563,
		["tickMod"] = false,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["minimapY"] = 712.76171875,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Lliliillili"] = "will buy spellcloth cd",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Jadow"] = "killed big guy in Nagrand",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Antiok"] = "has riding speed enchant!",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "no longer enchanter",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Gorefist"] = "will tank again (durnholde)",
			["Limmdul"] = "375 JC !gems",
			["Nocowlvl"] = "Welshman",
			["Eversia"] = "Kristine's Mage",
		},
		["guildNotes"] = {
		},
		["hideWorldMap"] = 1,
	},
	["CHAR-Vanisa-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["guildNotes"] = {
		},
		["hideGryphons"] = false,
		["tooltipRelocation"] = 1,
		["questTracker"] = 1,
		["minimapIcon"] = 1,
		["friendNotes"] = {
			["Ani"] = "Kristine",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Acani"] = "helped me",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Alandren"] = "Joe",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Nyum"] = "healed on RFK run",
			["Sadjah"] = "Erin",
			["Ardurren"] = "Matt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Furybringer"] = "Another pally we helped in STV",
			["Arolan"] = "Steve",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Antiok"] = "has riding speed enchant!",
			["Tjthepally"] = "pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Averin"] = "Joe's Alt",
			["Leetfade"] = "sold me Core of Earth",
			["Frostarical"] = "wants me to join guild soon",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
		},
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tooltipRelocationAnchor"] = false,
		["tickMod"] = false,
		["castingTimers"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Aona-Hellscream"] = {
		["minimapIcon"] = 1,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["guildNotes"] = {
		},
		["tooltipRelocationAnchor"] = false,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Lliliillili"] = "will buy spellcloth cd",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Jadow"] = "killed big guy in Nagrand",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Gorefist"] = "will tank again (durnholde)",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Antiok"] = "has riding speed enchant!",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "no longer enchanter",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Limmdul"] = "375 JC !gems",
			["Nocowlvl"] = "Welshman",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Pickpocket"] = "Karen",
		},
		["castingTimers"] = false,
		["minimapY"] = 712.76171875,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tickMod"] = false,
		["minimapX"] = 1214.766235351563,
		["questTracker"] = 1,
		["questTrackerAnchor"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Kabun-Laughing Skull"] = {
		["questTrackerAnchor"] = false,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["minimapIcon"] = 1,
		["guildNotes"] = {
		},
		["questTracker"] = 1,
		["castingTimers"] = false,
		["minimapY"] = 712.76171875,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tickMod"] = false,
		["minimapX"] = 1214.766235351563,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Lliliillili"] = "will buy spellcloth cd",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Jadow"] = "killed big guy in Nagrand",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Gorefist"] = "will tank again (durnholde)",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Antiok"] = "has riding speed enchant!",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "no longer enchanter",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Limmdul"] = "375 JC !gems",
			["Nocowlvl"] = "Welshman",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Pickpocket"] = "Karen",
		},
		["tooltipRelocationAnchor"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Rudeadyet-Hellscream"] = {
		["minimapIcon"] = 1,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["questTrackerAnchor"] = false,
		["questTracker"] = 1,
		["castingTimers"] = false,
		["tooltipRelocationAnchor"] = false,
		["minimapX"] = 1214.766235351563,
		["tickMod"] = false,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["minimapY"] = 712.76171875,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Jadow"] = "killed big guy in Nagrand",
			["Ani"] = "Kristine",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Frostarical"] = "wants me to join guild soon",
			["Antiok"] = "has riding speed enchant!",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Mindless"] = "no longer enchanter",
			["Furybringer"] = "Another pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Ardurren"] = "Matt",
			["Gorefist"] = "will tank again (durnholde)",
			["Limmdul"] = "375 JC !gems",
			["Nocowlvl"] = "Welshman",
		},
		["guildNotes"] = {
		},
		["hideWorldMap"] = 1,
	},
	["CHAR-Barimuri-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["guildNotes"] = {
		},
		["hideGryphons"] = false,
		["tooltipRelocation"] = 1,
		["questTracker"] = 1,
		["minimapIcon"] = 1,
		["friendNotes"] = {
			["Ani"] = "Kristine",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Acani"] = "helped me",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Alandren"] = "Joe",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Nyum"] = "healed on RFK run",
			["Sadjah"] = "Erin",
			["Ardurren"] = "Matt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Furybringer"] = "Another pally we helped in STV",
			["Arolan"] = "Steve",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Antiok"] = "has riding speed enchant!",
			["Tjthepally"] = "pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Averin"] = "Joe's Alt",
			["Leetfade"] = "sold me Core of Earth",
			["Frostarical"] = "wants me to join guild soon",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
		},
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tooltipRelocationAnchor"] = false,
		["tickMod"] = false,
		["castingTimers"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Chukk-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["guildNotes"] = {
		},
		["minimapIcon"] = 1,
		["tooltipRelocationAnchor"] = false,
		["questTracker"] = 1,
		["minimapX"] = 646.8573608398438,
		["tickMod"] = false,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["minimapY"] = 27.42833518981934,
		["castingTimers"] = false,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Lliliillili"] = "will buy spellcloth cd",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Jadow"] = "killed big guy in Nagrand",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Gorefist"] = "will tank again (durnholde)",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Antiok"] = "has riding speed enchant!",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "no longer enchanter",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Limmdul"] = "375 JC !gems",
			["Nocowlvl"] = "Welshman",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Pickpocket"] = "Karen",
		},
		["hideWorldMap"] = 1,
	},
	["CHAR-Phoebeldia-Laughing Skull"] = {
		["minimapIcon"] = 1,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["castingTimers"] = false,
		["friendNotes"] = {
			["Ani"] = "Kristine",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Acani"] = "helped me",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Alandren"] = "Joe",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Mindless"] = "+12 int to bracers enchant for 6g pst him lvl 35 bracer required",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Nyum"] = "healed on RFK run",
			["Sadjah"] = "Erin",
			["Ardurren"] = "Matt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Furybringer"] = "Another pally we helped in STV",
			["Arolan"] = "Steve",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Antiok"] = "has riding speed enchant!",
			["Tjthepally"] = "pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Averin"] = "Joe's Alt",
			["Leetfade"] = "sold me Core of Earth",
			["Frostarical"] = "wants me to join guild soon",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
		},
		["guildNotes"] = {
		},
		["questTrackerAnchor"] = false,
		["tickMod"] = false,
		["tooltipRelocationAnchor"] = false,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["questTracker"] = 1,
		["hideWorldMap"] = 1,
	},
	["CHAR-Tyrela-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["guildNotes"] = {
		},
		["minimapIcon"] = 1,
		["questTracker"] = 1,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Leetfade"] = "sold me Core of Earth",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Lilliana"] = "JC can cut moonstone",
			["Lliliillili"] = "will buy spellcloth cd",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Jadow"] = "killed big guy in Nagrand",
			["Rajjah"] = "rob",
			["Bulldyke"] = "healed for us, was awesome",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Kallsu"] = "priest, holy, nice guy",
			["Sadjah"] = "Erin",
			["Ani"] = "Kristine",
			["Frostarical"] = "wants me to join guild soon",
			["Gorefist"] = "will tank again (durnholde)",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Antiok"] = "has riding speed enchant!",
			["Furybringer"] = "Another pally we helped in STV",
			["Mindless"] = "no longer enchanter",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Limmdul"] = "375 JC !gems",
			["Nocowlvl"] = "Welshman",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Pickpocket"] = "Karen",
		},
		["minimapX"] = 1214.766235351563,
		["tickMod"] = false,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["minimapY"] = 712.76171875,
		["castingTimers"] = false,
		["tooltipRelocationAnchor"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Carrl-Auchindoun"] = {
		["questTrackerAnchor"] = false,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["guildNotes"] = {
		},
		["minimapIcon"] = false,
		["tooltipRelocationAnchor"] = false,
		["questTracker"] = 1,
		["minimapX"] = 1214.766235351563,
		["tickMod"] = false,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["minimapY"] = 712.76171875,
		["castingTimers"] = false,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Telah"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Vindex"] = "Ran SFK",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Deran"] = "Ran SFK",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Rhyydia"] = "Kris",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Limmdul"] = "375 JC !gems",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Ratafia"] = "hillsbrad qeusts",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Granas"] = "Ran SFK",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Gorefist"] = "will tank again (durnholde)",
			["Lilliana"] = "JC can cut moonstone",
			["Ani"] = "Kristine",
			["Bulldyke"] = "healed for us, was awesome",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Kallsu"] = "priest, holy, nice guy",
			["Rajjah"] = "rob",
			["Ashliy"] = "Ran SFK",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Nocowlvl"] = "Welshman",
			["Sadjah"] = "Erin",
			["Frostarical"] = "wants me to join guild soon",
			["Khainn"] = "Steve",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Italus"] = "HIllsbrad quests",
			["Antiok"] = "has riding speed enchant!",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Mindless"] = "no longer enchanter",
			["Furybringer"] = "Another pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Jadow"] = "killed big guy in Nagrand",
			["Rozah"] = "Matt",
			["Lliliillili"] = "will buy spellcloth cd",
			["Leetfade"] = "sold me Core of Earth",
		},
		["hideWorldMap"] = 1,
	},
	["CHAR-Knas-Auchindoun"] = {
		["questTrackerAnchor"] = false,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["minimapIcon"] = false,
		["guildNotes"] = {
		},
		["castingTimers"] = false,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Telah"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Vindex"] = "Ran SFK",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Deran"] = "Ran SFK",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Rhyydia"] = "Kris",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Limmdul"] = "375 JC !gems",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Ratafia"] = "hillsbrad qeusts",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Granas"] = "Ran SFK",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Gorefist"] = "will tank again (durnholde)",
			["Lilliana"] = "JC can cut moonstone",
			["Ani"] = "Kristine",
			["Bulldyke"] = "healed for us, was awesome",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Kallsu"] = "priest, holy, nice guy",
			["Rajjah"] = "rob",
			["Ashliy"] = "Ran SFK",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Nocowlvl"] = "Welshman",
			["Sadjah"] = "Erin",
			["Frostarical"] = "wants me to join guild soon",
			["Khainn"] = "Steve",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Italus"] = "HIllsbrad quests",
			["Antiok"] = "has riding speed enchant!",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Mindless"] = "no longer enchanter",
			["Furybringer"] = "Another pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Jadow"] = "killed big guy in Nagrand",
			["Rozah"] = "Matt",
			["Lliliillili"] = "will buy spellcloth cd",
			["Leetfade"] = "sold me Core of Earth",
		},
		["minimapY"] = 712.76171875,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["tickMod"] = false,
		["minimapX"] = 1214.766235351563,
		["questTracker"] = 1,
		["tooltipRelocationAnchor"] = false,
		["hideWorldMap"] = 1,
	},
	["CHAR-Ciid-Hellscream"] = {
		["questTrackerAnchor"] = false,
		["tooltipRelocation"] = 1,
		["hideGryphons"] = false,
		["guildNotes"] = {
		},
		["minimapIcon"] = false,
		["tooltipRelocationAnchor"] = false,
		["questTracker"] = 1,
		["minimapX"] = 1214.766235351563,
		["tickMod"] = false,
		["MOVABLE-TRACKERANCHOR"] = {
			"TOPLEFT", -- [1]
			nil, -- [2]
			"TOPLEFT", -- [3]
			1010.723754882813, -- [4]
			-213.0030975341797, -- [5]
			1, -- [6]
		},
		["minimapY"] = 712.76171875,
		["castingTimers"] = false,
		["friendNotes"] = {
			["Alandren"] = "Joe",
			["Telah"] = "Joe",
			["Kowala"] = "Helped us greatly in Hinterlands",
			["Acani"] = "helped me",
			["Kalzekath"] = "master enchanter, !enchant",
			["Kaliserna"] = "Will enchant minor speed,, just need mats",
			["Averin"] = "Joe's Alt",
			["Vindex"] = "Ran SFK",
			["Uub"] = "played in RFK did well",
			["Rickjamesb"] = "we helped him kill yeti's, he gave me some gems",
			["Raene"] = "Helped me get the Staff of the Sun!",
			["Deran"] = "Ran SFK",
			["Arolan"] = "Steve",
			["Tjthepally"] = "pally we helped in STV",
			["Nyum"] = "healed on RFK run",
			["Rhyydia"] = "Kris",
			["Baryleris"] = "has spellstrike hood and battlecast hood",
			["Limmdul"] = "375 JC !gems",
			["Neobarbaric"] = "helped quests in barrens",
			["Grenkar"] = "sold me mithril spurs on the cheap, get more form him!",
			["Ratafia"] = "hillsbrad qeusts",
			["Snagscuha"] = "played in RFK, mage, undead",
			["Holyschmitt"] = "has Great Dawnstone",
			["Granas"] = "Ran SFK",
			["Hinotay"] = "We helped him kill humans, he made us free stuff",
			["Arkai"] = "Mage we fought with in the mine",
			["Gorefist"] = "will tank again (durnholde)",
			["Lilliana"] = "JC can cut moonstone",
			["Ani"] = "Kristine",
			["Bulldyke"] = "healed for us, was awesome",
			["Fluffywontok"] = "said he'd help with eng mount",
			["Kallsu"] = "priest, holy, nice guy",
			["Rajjah"] = "rob",
			["Ashliy"] = "Ran SFK",
			["Chrillex"] = "Paid him some gold, he owes me",
			["Nocowlvl"] = "Welshman",
			["Sadjah"] = "Erin",
			["Frostarical"] = "wants me to join guild soon",
			["Khainn"] = "Steve",
			["Arkanist"] = "Enchnater, says he has most enchats.. ",
			["Ardurren"] = "Matt",
			["Italus"] = "HIllsbrad quests",
			["Antiok"] = "has riding speed enchant!",
			["Seniorage"] = "ran us through hinterlands thingy",
			["Mindless"] = "no longer enchanter",
			["Furybringer"] = "Another pally we helped in STV",
			["Jefeisthebes"] = "starting a guild, invited us, might be active, lots of high lvlers",
			["Dapain"] = "ran BRD",
			["Jadow"] = "killed big guy in Nagrand",
			["Rozah"] = "Matt",
			["Lliliillili"] = "will buy spellcloth cd",
			["Leetfade"] = "sold me Core of Earth",
		},
		["hideWorldMap"] = 1,
	},
}
