
DBM_SavedVars = {
	["AddOns"] = {
		["Akilzon"] = {
			["Enabled"] = true,
			["RangeCheck"] = true,
			["BAREnrage"] = true,
			["BARElectrical Storm"] = true,
			["Announce"] = false,
		},
		["RomuloAndJulianne"] = {
			["Enabled"] = true,
			["WarnHeal"] = true,
			["BARHeal"] = true,
			["Announce"] = false,
			["PosionWarn"] = true,
		},
		["Gruul"] = {
			["SilenceWarn"] = false,
			["BARGround Slam"] = true,
			["RangeCheck"] = true,
			["ShatterWarn"] = true,
			["SpecWarning"] = true,
			["Enabled"] = true,
			["Announce"] = false,
			["BARSilence"] = true,
			["BARGrow #(%d+)"] = true,
			["BARShatter"] = true,
			["GrowWarn"] = true,
		},
		["Janalai"] = {
			["Enabled"] = true,
			["BARExplosion"] = true,
			["BARHatcher"] = true,
			["Announce"] = false,
			["BAREnrage"] = true,
		},
		["Hyakiss"] = {
			["Enabled"] = true,
			["Announce"] = false,
		},
		["Aran"] = {
			["BARFlame Wreath Cast"] = true,
			["BARArcane Explosion"] = true,
			["BARFlame Wreath"] = true,
			["BARBlizzard"] = true,
			["Enabled"] = true,
			["Announce"] = false,
			["BARElementals despawn in"] = true,
		},
		["Moroes"] = {
			["Enabled"] = true,
			["VanishWarn"] = true,
			["VanishWarnSoon"] = true,
			["GarroteWarn"] = true,
			["VanishWarnFade"] = true,
			["Announce"] = false,
			["BARVanish"] = true,
		},
		["Kazzak"] = {
			["Enabled"] = true,
			["BARMark of Kazzak"] = true,
			["Announce"] = false,
			["Whisper"] = false,
			["BAREnrage"] = true,
			["TwistedWarn"] = true,
			["EnrageWarn"] = true,
			["Icon"] = true,
			["MarkWarn"] = true,
		},
		["Rage"] = {
			["IceIcon"] = false,
			["BARDeath & Decay"] = true,
			["Enabled"] = true,
			["WarnDnDSoon"] = true,
			["WarnDnD"] = true,
			["BARNext Death & Decay"] = true,
			["Announce"] = false,
			["WarnIce"] = true,
		},
		["Arathi"] = {
			["Enabled"] = true,
			["ShowAbFrame"] = true,
			["Announce"] = false,
			["ShowAbBasesToWin"] = true,
		},
		["Anetheron"] = {
			["Enabled"] = true,
			["WarnCarrion"] = true,
			["WarnInferno"] = true,
			["BARInfernal"] = true,
			["Announce"] = false,
		},
		["Rokad"] = {
			["Enabled"] = true,
			["Announce"] = false,
		},
		["Netherspite"] = {
			["PhaseWarn"] = true,
			["BARPortal Phase"] = true,
			["BARBanish Phase"] = true,
			["BARNetherbreath"] = true,
			["VoidWarn"] = true,
			["BreathWarn"] = true,
			["PhasePreWarn"] = true,
			["BAREnrage"] = true,
			["Announce"] = false,
			["Enabled"] = true,
		},
		["Arenas"] = {
			["Enabled"] = true,
			["Announce"] = false,
		},
		["Magtheridon"] = {
			["WarnNova"] = true,
			["Enabled"] = true,
			["BARPhase 2"] = true,
			["Announce"] = false,
			["BARBlast Nova"] = true,
			["BARHeal"] = true,
			["WarnHeal"] = true,
			["WarnInfernal"] = true,
		},
		["Alterac"] = {
			["Enabled"] = true,
			["AutoTurnIn"] = true,
			["Announce"] = false,
			["Flash"] = false,
		},
		["TerestianIllhoof"] = {
			["Enabled"] = true,
			["BARSacrifice"] = true,
			["BARWeakened"] = true,
			["Announce"] = false,
			["WarnSoon"] = true,
		},
		["Archimonde"] = {
			["Enabled"] = true,
			["Burst"] = false,
			["BurstSpecWarn"] = true,
			["Grip"] = true,
			["BARFear"] = true,
			["BurstSay"] = true,
			["BAREnrage"] = true,
			["BurstIcon"] = true,
			["Announce"] = false,
		},
		["EyeOfTheStorm"] = {
			["Enabled"] = true,
			["Announce"] = false,
			["ShowPointFrame"] = true,
		},
		["Maulgar"] = {
			["BARNext Whirlwind"] = true,
			["BARWhirlwind"] = true,
			["Enabled"] = true,
			["Announce"] = false,
			["BARFelhunter"] = true,
			["BARArcing Smash"] = true,
			["WarnHeal"] = false,
			["BARHeal"] = true,
			["BARSpell Shield: (.*)"] = true,
			["WarnPoH"] = false,
			["WarnWW"] = true,
			["WarnPWS"] = true,
			["WarnFelhunter"] = true,
			["WarnSpellShield"] = true,
			["BARPrayer of Healing"] = true,
			["WarnSmash"] = false,
		},
		["LurkerBelow"] = {
			["Enabled"] = true,
			["SpoutWarn"] = true,
			["BAREmerge"] = true,
			["BARSpout"] = true,
			["WhirlWarn"] = true,
			["WhirlSoonWarn"] = true,
			["BARNext Spout"] = true,
			["BARSubmerge"] = true,
			["Announce"] = false,
			["BARWhirl"] = true,
		},
		["Attumen"] = {
			["BARCurse"] = true,
			["Enabled"] = true,
			["Announce"] = false,
			["PreWarning"] = false,
		},
		["BigBadWolf"] = {
			["BARFear"] = true,
			["FearWarn"] = true,
			["Whisper"] = true,
			["Enabled"] = true,
			["BARNext Red Riding Hood"] = true,
			["Announce"] = false,
			["BARRed Riding Hood"] = true,
		},
		["MHT"] = {
			["Enabled"] = true,
			["Mobs"] = false,
			["BARNext Wave"] = true,
			["Ghoul"] = false,
			["Announce"] = false,
		},
		["ZulJin"] = {
			["Enabled"] = true,
			["Announce"] = false,
			["WarnLynx"] = true,
			["WarnPara"] = true,
		},
		["Azgalor"] = {
			["Enabled"] = true,
			["BARDoom: (.*)"] = true,
			["Announce"] = false,
			["BARSilence"] = true,
			["WarnSilence"] = true,
			["DoomIcon"] = true,
		},
		["Vashj"] = {
			["WarnLoot"] = true,
			["IconLoot"] = true,
			["IconCharge"] = false,
			["RangeCheck"] = true,
			["BARStrider"] = true,
			["WarnSpawns"] = true,
			["BARStatic Charge: (.*)"] = true,
			["WarnCharge"] = true,
			["SpecWarnLoot"] = true,
			["Enabled"] = true,
			["BARNaga"] = true,
			["Announce"] = false,
			["BARTainted Elemental"] = true,
		},
		["Malacrass"] = {
			["Enabled"] = true,
			["BARSpirit Bolts"] = true,
			["BARNext Spirit Bolts"] = true,
			["BARSiphon Soul: (.*)"] = true,
			["Announce"] = false,
		},
		["KaelThas"] = {
			["BARPhoenix"] = true,
			["BARNext Shock Barrier"] = true,
			["ThalaIcon"] = true,
			["BARGravity Lapse"] = true,
			["BARShock Barrier"] = true,
			["BARFear"] = true,
			["WarnGravity"] = true,
			["ThalaWhisper"] = true,
			["WarnMC"] = true,
			["WarnFearSoon"] = true,
			["WarnBarrier"] = true,
			["WarnToy"] = true,
			["BARConflagration: (.*)"] = true,
			["BARPhase 4"] = true,
			["BARPhase 3"] = true,
			["Announce"] = false,
			["BARLord Sanguinar"] = true,
			["TimerConflag2"] = false,
			["RangeCheck"] = true,
			["WarnPhase"] = true,
			["BARGaze Cooldown"] = true,
			["WarnConflag2"] = false,
			["IconMC"] = true,
			["ShowAddFrame"] = true,
			["BARNext Fear"] = true,
			["ShowFrame"] = true,
			["WarnFear"] = true,
			["Enabled"] = true,
			["WarnBarrier2"] = false,
			["WarnConflag"] = true,
			["WarnPyro"] = false,
			["BARThaladred"] = true,
			["BARCapernian"] = true,
			["BARNext Gravity Lapse"] = true,
			["BARRemote Toy: (.*)"] = true,
			["BARRebirth"] = true,
			["BARTelonicus"] = true,
			["BARPyroblast"] = true,
			["WarnPhoenix"] = true,
		},
		["Oz"] = {
			["Enabled"] = true,
			["BARRoar"] = true,
			["BARTinhead"] = true,
			["RangeCheck"] = true,
			["BARStrawman"] = true,
			["Announce"] = false,
			["BARTito"] = true,
		},
		["Kazrogal"] = {
			["Enabled"] = true,
			["Announce"] = false,
		},
		["Fathomlord"] = {
			["BARHealing Wave"] = true,
			["Heal"] = true,
			["KaraTotem"] = true,
			["TidalTotem"] = true,
			["BAREnrage"] = true,
			["Announce"] = false,
			["Enabled"] = true,
		},
		["Battlegrounds"] = {
			["Enabled"] = true,
			["ShowInviteTimer"] = true,
			["ColorByClass"] = true,
			["AutoSpirit"] = false,
			["Announce"] = false,
		},
		["Nalorakk"] = {
			["SilenceWarn"] = true,
			["PrePhaseWarn"] = true,
			["BARBear Form"] = true,
			["BARNormal Form"] = true,
			["Announce"] = false,
			["Enabled"] = true,
		},
		["Hydross"] = {
			["Enabled"] = true,
			["BARMark of Corruption #(%d+)"] = true,
			["MarkPreWarn"] = false,
			["RangeCheck"] = true,
			["Phases"] = true,
			["Marks"] = true,
			["WaterTomb"] = true,
			["BARWater Tomb"] = true,
			["BAREnrage"] = true,
			["Announce"] = false,
			["BARMark of Hydross #(%d+)"] = true,
		},
		["Prince"] = {
			["WarnInfernal"] = true,
			["BAREnfeeble"] = true,
			["SendWhisper"] = false,
			["WarnSWP"] = true,
			["WarnEnfeeble"] = true,
			["Enabled"] = true,
			["BARShadow Nova"] = true,
			["BARInfernal"] = true,
			["Announce"] = false,
			["WarnNova"] = true,
		},
		["Tidewalker"] = {
			["Murlocs"] = true,
			["BARMurlocs"] = true,
			["BARWatery Grave"] = true,
			["Grave"] = false,
			["Announce"] = false,
			["Enabled"] = true,
		},
		["Doomwalker"] = {
			["Enabled"] = true,
			["BAREarthquake Cooldown"] = true,
			["ChargeWarn"] = true,
			["BAROverrun Cooldown"] = true,
			["RangeCheck"] = true,
			["BAREarthquake"] = true,
			["Announce"] = false,
			["QuakeWarn"] = true,
		},
		["Warsong"] = {
			["Enabled"] = true,
			["ShowFlagCarrierErrorNote"] = false,
			["ShowFlagCarrier"] = true,
			["Announce"] = false,
		},
		["VoidReaver"] = {
			["WarnOrb"] = false,
			["YellOrb"] = true,
			["SoundWarning"] = false,
			["IconOrb"] = false,
			["BARNext Pounding"] = true,
			["WarnPoundingSoon"] = true,
			["BARPounding"] = true,
			["BAREnrage"] = true,
			["WarnPounding"] = true,
			["Announce"] = false,
			["Enabled"] = true,
		},
		["Curator"] = {
			["Enabled"] = true,
			["BAREvocation"] = true,
			["RangeCheck"] = true,
			["BARNext Evocation"] = true,
			["Announce"] = false,
		},
		["Halazzi"] = {
			["Enabled"] = true,
			["Frenzy"] = true,
			["Announce"] = false,
			["Totem"] = true,
		},
		["Nightbane"] = {
			["Enabled"] = true,
			["CharredEarth"] = true,
			["BARFear"] = true,
			["BARAir Phase"] = true,
			["Ash"] = false,
			["BARNightbane"] = true,
			["BoneRain"] = true,
			["Announce"] = false,
			["BARNext Fear"] = true,
		},
		["Maiden"] = {
			["BARRepentance"] = true,
			["BARNext Repentance"] = true,
			["RangeCheck"] = true,
			["HolyFireWarn"] = true,
			["Announce"] = false,
			["Enabled"] = true,
		},
		["Leotheras"] = {
			["BARNext Whirlwind"] = true,
			["BARWhirlwind"] = true,
			["WhirlWarn"] = true,
			["BARInner Demons"] = true,
			["WarnDemons"] = false,
			["DemonWarn"] = true,
			["BARDemon Form"] = true,
			["BARNormal Form"] = true,
			["BAREnrage"] = true,
			["Announce"] = false,
			["Enabled"] = true,
		},
		["Alar"] = {
			["BARMelt Armor: (.*)"] = true,
			["Meteor"] = true,
			["WarnArmor"] = true,
			["BARMeteor"] = true,
			["BAREnrage"] = true,
			["Announce"] = false,
			["Enabled"] = true,
		},
		["Solarian"] = {
			["Enabled"] = true,
			["IconWrath"] = true,
			["BARAgents"] = true,
			["BARSplit"] = true,
			["SoundWarning"] = false,
			["WarnPhase"] = true,
			["SpecWrath"] = true,
			["BARWrath: (.*)"] = true,
			["WhisperWrath"] = true,
			["WarnWrath"] = true,
			["BARPriests & Solarian"] = true,
			["Announce"] = false,
		},
		["Shadikith"] = {
			["Enabled"] = true,
			["Announce"] = false,
		},
	},
	["DBM"] = {
		["FirstTimeLoaded790"] = false,
		["BusyMessage"] = "%P is busy. (Fighting against %B - %HP - %ALIVE/%RAID people alive) You will be informed after the fight. Whisper \"status\" to query the raid's status.",
		["FlashEnabled"] = true,
		["FirstTimeLoaded770"] = false,
		["ShowIcon"] = true,
		["AutoRespond"] = true,
		["SpecialWarningTextSize"] = 40,
		["RaidWarningColors"] = {
			{
				["b"] = 0.94,
				["g"] = 0.8,
				["r"] = 0.41,
			}, -- [1]
			{
				["b"] = 0,
				["g"] = 0.95,
				["r"] = 0.95,
			}, -- [2]
			{
				["b"] = 0,
				["g"] = 0.5,
				["r"] = 1,
			}, -- [3]
			{
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			}, -- [4]
			{
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.05,
			}, -- [5]
		},
		["LoadGUIOnLoad"] = false,
		["EnableSync"] = true,
		["StatusBarColor"] = {
			["a"] = 1,
			["b"] = 0,
			["g"] = 0.7,
			["r"] = 1,
		},
		["StatusBarSize"] = {
			["Scale"] = 0.75,
			["Text"] = 13,
			["Width"] = 255,
		},
		["ShowAutoRespondInfo"] = true,
		["EnableStatusBars"] = true,
		["EnlargeBarsAfterSec"] = 7.5,
		["SpecialWarningsEnabled"] = true,
		["Gui"] = {
			["SelfWarning_PosY"] = 235,
			["RaidWarning_G"] = 0.858823,
			["RaidWarning_PosX"] = 0,
			["PizzaTimerSec"] = 0,
			["RaidWarning_B"] = 0.717647,
			["CombatLogValue"] = 2,
			["SelfWarning_PosX"] = 0,
			["HidePlayerNamesInRaid"] = false,
			["RaidWarning_Font"] = "Fonts\\FRIZQT__.TTF",
			["RaidWarning_PosY"] = -235,
			["PizzaTimerHour"] = 0,
			["SelfWarning_Enable"] = false,
			["PizzaTimerBroadcast"] = true,
			["RaidWarnSound"] = 1,
			["RaidWarning_Enable"] = true,
			["SelfWarning_R"] = 1,
			["SelfWarning_G"] = 0.858823,
			["SelfWarning_B"] = 0.717647,
			["SelfWarning_Delay"] = 5,
			["PizzaTimerMin"] = 15,
			["SelfWarning_Height"] = 16,
			["Version"] = "3.01",
			["RaidWarning_R"] = 1,
			["RaidWarning_Height"] = 18,
			["PizzaTimerText"] = "Pizza",
			["SelfWarning_Font"] = "Fonts\\FRIZQT__.TTF",
			["RaidWarning_Delay"] = 1,
		},
		["SpecialWarningTextFadeTime"] = 3,
		["SpecialWarningTextColor"] = {
			["a"] = 1,
			["b"] = 1,
			["g"] = 0,
			["r"] = 0,
		},
		["CharSettings"] = {
			["Xuyxee"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroLocalWarning"] = false,
			},
			["Nohsk"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroLocalWarning"] = false,
			},
			["Unlok"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Carrl"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Ciid"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Pandohra"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Aonar"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroLocalWarning"] = false,
			},
			["Thunderdome"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Tyrela"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Barimuri"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroLocalWarning"] = false,
			},
			["Rudeadyet"] = {
				["AggroShake"] = false,
				["AggroFlash"] = false,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = false,
				["AggroAlert"] = false,
				["AggroSound"] = false,
				["AggroLocalWarning"] = false,
			},
			["Scid"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = false,
				["AggroShake"] = false,
				["AggroSound"] = false,
				["AggroAlert"] = false,
				["AggroSpecialWarning"] = false,
				["AggroLocalWarning"] = false,
			},
			["Anokank"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroLocalWarning"] = false,
			},
			["Chukk"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroLocalWarning"] = false,
			},
			["Aonarap"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Aona"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroLocalWarning"] = false,
			},
			["Nideyn"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroLocalWarning"] = false,
			},
			["Pulari"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroLocalWarning"] = false,
			},
			["Prudey"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Tamori"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Japhaar"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Knas"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Bairra"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroLocalWarning"] = false,
			},
			["Kabun"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroSound"] = false,
				["AggroAlert"] = true,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Aset"] = {
				["AggroShake"] = true,
				["AggroFlash"] = true,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroLocalWarning"] = false,
			},
			["Irone"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Zik"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
			["Xanaomi"] = {
				["AggroShake"] = false,
				["AggroFlash"] = false,
				["AggroAlertInAllInstances"] = false,
				["AggroSpecialWarning"] = false,
				["AggroAlert"] = false,
				["AggroSound"] = false,
				["AggroLocalWarning"] = false,
			},
			["Freezeforu"] = {
				["AggroAlertInAllInstances"] = false,
				["AggroFlash"] = true,
				["AggroShake"] = true,
				["AggroAlert"] = true,
				["AggroSound"] = false,
				["AggroSpecialWarning"] = true,
				["AggroLocalWarning"] = false,
			},
		},
		["Level70Gui"] = true,
		["FirstTimeLoaded879"] = false,
		["EnlargeBarsAfterPerc"] = 10,
		["EnlargeBarsMaxSec"] = 20,
		["ShakeIntensity"] = 30,
		["HugeBars"] = {
			["StatusBarDesign"] = 2,
			["AutoColorBars"] = true,
			["StatusBarColor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0.7,
				["r"] = 1,
			},
			["StatusBarSize"] = {
				["Scale"] = 1.05,
				["Text"] = 11,
				["Width"] = 218,
			},
			["StatusBarsFlippedOver"] = false,
			["EnableStatusBars"] = true,
			["ShowIcon"] = true,
			["FlashBars"] = true,
			["IconRight"] = false,
			["FillUpStatusBars"] = true,
			["MaxStatusBars"] = 10,
		},
		["IconRight"] = false,
		["FirstTime679Loaded"] = false,
		["ShakeEnabled"] = false,
		["EnableStatusCommand"] = true,
		["SpamBlock"] = {
			["CTRaidFrame"] = true,
			["RaidWarningChat"] = false,
			["RaidWarningFrame"] = false,
			["Battleground"] = true,
			["RaidChat"] = true,
		},
		["MaxStatusBars"] = 15,
		["StatusBarDesign"] = 2,
		["AutoColorBars"] = true,
		["FlashColor"] = "red",
		["ShowPullSyncInfo"] = false,
		["ShowCombatInformations"] = true,
		["NumFlashes"] = 1,
		["FlashDuration"] = 2,
		["StatusBarsFlippedOver"] = false,
		["HideOutgoingInfoWhisper"] = true,
		["ShakeDuration"] = 0.5,
		["ShowWhispersDuringCombat"] = true,
		["FlashBars"] = true,
		["SpecialWarningTextDuration"] = 5,
		["AllowSyncFromOldVersions"] = true,
		["MinimapButton"] = {
			["Enabled"] = false,
			["Radius"] = 82.2,
			["Position"] = 200,
		},
		["FillUpStatusBars"] = true,
	},
}
DBMInfoFramePositions = {
	["Advisors"] = {
		["y"] = -461.71438114617,
		["x"] = 1793.142881964787,
	},
	["Distance"] = {
		["y"] = -374.4508056640625,
		["x"] = 1510.984741210938,
	},
	["Weapons"] = {
		["y"] = -406.8571984454122,
		["x"] = 1652.571585214673,
	},
}
