
kgPanelsDB = {
	["profileKeys"] = {
		["Chukk - Auchindoun"] = "Default",
		["Karrl - Auchindoun"] = "Default",
		["Wezen - Auchindoun"] = "Default",
		["Knasbank - Auchindoun"] = "Default",
		["Aset - Auchindoun"] = "Default",
		["Pulari - Auchindoun"] = "Default",
		["Promitto - Auchindoun"] = "Default",
		["Pandohra - Auchindoun"] = "Default",
		["Aonah - Auchindoun"] = "Default",
	},
	["global"] = {
		["version"] = 2,
		["layouts"] = {
			["Chukk"] = {
				["Bottom"] = {
					["bg_orientation"] = "HORIZONTAL",
					["strata"] = "BACKGROUND",
					["scripts"] = {
					},
					["anchorTo"] = "CENTER",
					["parent"] = "UIParent",
					["absolute_bg"] = {
						["LRy"] = 1,
						["LRx"] = 1,
						["ULx"] = 0,
						["ULy"] = 0,
						["URx"] = 1,
						["URy"] = 0,
						["LLx"] = 0,
						["LLy"] = 1,
					},
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["bg_insets"] = {
						["b"] = -4,
						["t"] = 4,
						["l"] = -4,
						["r"] = 4,
					},
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "None",
					["anchor"] = "UIParent",
					["level"] = 0,
					["text"] = {
						["y"] = 0,
						["font"] = "Blizzard",
						["justifyH"] = "CENTER",
						["x"] = 0,
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["y"] = -507.2858454643904,
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_color"] = {
						["a"] = 0,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_texture"] = "Blizzard Tooltip",
					["bg_color"] = {
						["a"] = 1,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
					["width"] = "1928",
					["rotation"] = 0,
					["x"] = -0.4288216862369252,
					["bg_alpha"] = 1,
					["border_edgeSize"] = 16,
					["height"] = "205",
					["mouse"] = false,
					["crop"] = false,
					["tiling"] = false,
				},
			},
		},
	},
	["profiles"] = {
		["Default"] = {
			["layout"] = "Chukk",
		},
	},
}
