
nivcfgDB = {
	["hmSHAM"] = false,
	["colorClassHealth"] = false,
	["ptShowPortrait"] = false,
	["cbTextLenTF"] = 10,
	["showIcons"] = true,
	["texMana"] = "Healbot",
	["ftX"] = -2,
	["colorClassMana"] = true,
	["colorBg"] = {
		["a"] = 0.75,
		["b"] = 1,
		["g"] = 1,
		["r"] = 1,
	},
	["fontHeightN"] = 8,
	["cbTextLen"] = 30,
	["ptPortraitHeight"] = 10,
	["partyY"] = 118,
	["prNameLenHM"] = 5,
	["autoHMtoggle"] = true,
	["castbarWidth"] = 302,
	["totX"] = 2,
	["ptHeight"] = 28,
	["hmDRUID"] = false,
	["ptPortraitWidth"] = 28,
	["tfManaHeight"] = 3.5,
	["partyX"] = 909.5,
	["hmMAGE"] = false,
	["enablePR"] = true,
	["tfHealthHeight"] = 16,
	["castBarTTF"] = true,
	["prManaHeight"] = 3.5,
	["targetSym"] = true,
	["totY"] = -8,
	["petY"] = -2,
	["debuffs"] = {
		["player"] = {
			["enabled"] = true,
			["combine"] = false,
			["pos"] = "TopRight",
		},
		["focus"] = {
			["enabled"] = false,
			["combine"] = false,
			["pos"] = "BottomRight",
		},
		["target"] = {
			["enabled"] = true,
			["combine"] = true,
			["pos"] = "TopLeft",
		},
		["pet"] = {
			["enabled"] = false,
			["combine"] = false,
			["pos"] = "BottomRight",
		},
		["targettarget"] = {
			["enabled"] = false,
			["combine"] = false,
			["pos"] = "BottomRight",
		},
	},
	["ptManaHeight"] = 5,
	["prNameLen"] = 4,
	["castbarY"] = -205,
	["tttY"] = 0,
	["buffSize"] = 14,
	["prWidth"] = 23,
	["tttX"] = 2,
	["hmPRIEST"] = false,
	["petManaHeight"] = 1,
	["playerY"] = 123,
	["hmHUNTER"] = false,
	["hmPALA"] = false,
	["colorReactMana"] = true,
	["targetY"] = 0,
	["buffs"] = {
		["player"] = {
			["enabled"] = false,
			["pos"] = "LeftBottom",
		},
		["focus"] = {
			["enabled"] = false,
			["pos"] = "TopRight",
		},
		["target"] = {
			["enabled"] = true,
			["pos"] = "TopLeft",
		},
		["pet"] = {
			["enabled"] = false,
			["pos"] = "TopRight",
		},
		["targettarget"] = {
			["enabled"] = false,
			["pos"] = "TopRight",
		},
	},
	["raidOffset"] = -3,
	["hmDK"] = false,
	["verticalGroups"] = true,
	["hmWL"] = false,
	["enableFT"] = false,
	["petHeight"] = 11,
	["fontNames"] = "Friz Quadrata TT",
	["fontHeightV"] = 8,
	["focusY"] = -8,
	["cbPosTF"] = "Bottom",
	["hmROGUE"] = false,
	["prHealthHeightHM"] = 23,
	["tfHeight"] = 21,
	["healerMode"] = false,
	["hmverticalGroups"] = false,
	["ptHealthHeight"] = 22,
	["fontValues"] = "Friz Quadrata TT",
	["targetX"] = 30,
	["dbHighlightFilter"] = true,
	["debuffSize"] = 14,
	["petHealthHeight"] = 9,
	["texHealth"] = "Healbot",
	["names"] = {
		["player"] = {
			["enabled"] = true,
			["pos"] = "Bottom",
		},
		["targettargettarget"] = {
			["enabled"] = true,
			["pos"] = "Top",
		},
		["focus"] = {
			["enabled"] = true,
			["pos"] = "Top",
		},
		["target"] = {
			["enabled"] = true,
			["pos"] = "Bottom",
		},
		["focustarget"] = {
			["enabled"] = true,
			["pos"] = "Top",
		},
		["targettarget"] = {
			["enabled"] = true,
			["pos"] = "Top",
		},
	},
	["colorReactHealth"] = false,
	["ptPortraitSym"] = true,
	["prHeight"] = 19,
	["castbarX"] = 0,
	["hmpartyX"] = 410,
	["focusX"] = -2,
	["ptPortraitPos"] = "Left",
	["ftY"] = 0,
	["hmraidOffset"] = -3,
	["playerX"] = 380,
	["tfWidth"] = 100,
	["enableTTT"] = false,
	["castBar"] = true,
	["prHeightHM"] = 28,
	["unlocked"] = false,
	["colorHealth"] = {
		["a"] = 1,
		["b"] = 0.45,
		["g"] = 0.35,
		["r"] = 0.35,
	},
	["prManaHeightHM"] = 3.5,
	["petWidth"] = 50,
	["hmWARR"] = false,
	["petX"] = 0,
	["hmpartyY"] = 450,
	["ptWidth"] = 140,
	["prWidthHM"] = 33,
	["prHealthHeight"] = 14,
}
