
PowaGlobalSet = {
	[121] = {
		["gcd"] = false,
		["b"] = 1,
		["anim1"] = 1,
		["g"] = 1,
		["thresholdinvert"] = false,
		["tooltipCheck"] = "",
		["Instance25ManHeroic"] = 0,
		["stacksLower"] = 0,
		["target"] = false,
		["icon"] = "",
		["beginSpin"] = false,
		["buffname"] = "Rake",
		["r"] = 1,
		["Extra"] = false,
		["begin"] = 0,
		["PowerType"] = -1,
		["customsoundend"] = "",
		["customname"] = "",
		["RoleMeleDps"] = 0,
		["groupany"] = true,
		["isAlive"] = true,
		["timerduration"] = 0,
		["unitn"] = "",
		["bufftype"] = 2,
		["stacks"] = 0,
		["focus"] = false,
		["Instance10ManHeroic"] = 0,
		["raid"] = false,
		["texture"] = 174,
		["alpha"] = 0.6599999666213989,
		["aurastext"] = "",
		["InstanceBg"] = 0,
		["symetrie"] = 1,
		["Timer"] = {
			["a"] = 1,
			["b"] = 1,
			["HideLeadingZeros"] = false,
			["g"] = 1,
			["h"] = 1,
			["ShowOnAuraHide"] = false,
			["UpdatePing"] = false,
			["Texture"] = "Default",
			["enabled"] = false,
			["r"] = 1,
			["cents"] = true,
			["Relative"] = "NONE",
			["y"] = 0,
			["x"] = 0,
			["id"] = 121,
			["Transparent"] = false,
			["Showing"] = false,
			["UseOwnColor"] = false,
			["ShowActivation"] = false,
			["Seconds99"] = false,
		},
		["Stacks"] = {
			["a"] = 1,
			["b"] = 1,
			["HideLeadingZeros"] = false,
			["g"] = 1,
			["LegacySizing"] = false,
			["UpdatePing"] = false,
			["Texture"] = "Default",
			["enabled"] = false,
			["r"] = 1,
			["Showing"] = false,
			["Relative"] = "NONE",
			["y"] = 0,
			["x"] = 0,
			["Transparent"] = false,
			["UseOwnColor"] = false,
			["id"] = 121,
			["h"] = 1,
		},
		["owntex"] = false,
		["isResting"] = false,
		["HideRequest"] = false,
		["RoleRangeDps"] = 0,
		["mine"] = true,
		["Active"] = false,
		["Showing"] = false,
		["multiids"] = "",
		["customtex"] = false,
		["inVehicle"] = false,
		["speed"] = 1,
		["Instance5Man"] = 0,
		["sound"] = 0,
		["spec1"] = true,
		["stacksOperator"] = ">=",
		["realaura"] = 1,
		["finish"] = 1,
		["anim2"] = 0,
		["customsound"] = "",
		["threshold"] = 50,
		["exact"] = false,
		["ismounted"] = false,
		["textaura"] = false,
		["spec2"] = true,
		["ignoremaj"] = true,
		["wowtex"] = false,
		["groupOrSelf"] = false,
		["strata"] = "LOW",
		["soundend"] = 0,
		["y"] = -4,
		["InstanceArena"] = 0,
		["inParty"] = 0,
		["randomcolor"] = false,
		["torsion"] = 1,
		["aurastextfont"] = 1,
		["RoleTank"] = 0,
		["isSecondary"] = false,
		["Instance10Man"] = 0,
		["Instance25Man"] = 0,
		["PvP"] = 0,
		["party"] = false,
		["combat"] = 0,
		["optunitn"] = false,
		["size"] = 0.75,
		["inRaid"] = 0,
		["Instance5ManHeroic"] = 0,
		["id"] = 121,
		["UseOldAnimations"] = false,
		["InvertAuraBelow"] = 0,
		["duration"] = 0,
		["RoleHealer"] = 0,
		["texmode"] = 1,
		["inverse"] = false,
		["GTFO"] = 0,
		["targetfriend"] = false,
		["x"] = 113,
		["off"] = true,
		["stance"] = 10,
	},
}
PowaGlobalListe = {
	"Global 1", -- [1]
	"Global 2", -- [2]
	"Global 3", -- [3]
	"Global 4", -- [4]
	"Global 5", -- [5]
	"Global 6", -- [6]
	"Global 7", -- [7]
	"Global 8", -- [8]
	"Global 9", -- [9]
	"Global 10", -- [10]
}
PowaGlobalMisc = {
	["PathToSounds"] = "Interface\\AddOns\\PowerAuras\\Sounds\\",
	["PathToAuras"] = "Interface\\Addons\\PowerAuras\\Custom\\",
	["BlockIncomingAuras"] = false,
	["FixExports"] = false,
}
