
TidyPlatesHubTankCache = {
	["ColorAttackingOtherTank"] = {
		["r"] = 0.5215686274509804,
		["g"] = 1,
		["b"] = 0,
	},
	["OpacitySpotlight"] = 0.5,
	["OpacityTarget"] = 1,
	["ScaleIgnoreNeutralUnits"] = false,
	["ClassPartyIcon"] = false,
	["WidgetsDebuffList"] = {
		["Lacerate"] = true,
		["Rake"] = true,
		["Rip"] = true,
	},
	["ColorAttackingOthers"] = {
		["r"] = 1,
		["g"] = 0.5019607843137255,
		["b"] = 0,
	},
	["OpacityFilterNonElite"] = false,
	["OpacitySpotlightMode"] = 1,
	["OpacityFullNoTarget"] = true,
	["ColorDangerGlowMode"] = 1,
	["WidgetTargetHighlight"] = true,
	["WidgetsThreatIndicator"] = true,
	["TextHealthTextMode"] = 1,
	["WidgetsTotemIcon"] = false,
	["ColorDangerGlowOnParty"] = false,
	["ScaleStandard"] = 1,
	["OpacityNonTarget"] = 0.5,
	["ColorHealthBarMode"] = 3,
	["WidgetsRangeIndicator"] = false,
	["OpacityFilterCustom"] = {
		["Fanged Pit Viper"] = true,
	},
	["ColorAggroTransition"] = {
		["r"] = 1,
		["g"] = 0.8470588235294118,
		["b"] = 0,
	},
	["TextShowLevel"] = false,
	["ScaleSpotlightMode"] = 4,
	["OpacityFilterNeutralUnits"] = false,
	["WidgetEliteIndicator"] = true,
	["WidgetsThreatIndicatorMode"] = 1,
	["OpacityFullSpell"] = false,
	["FrameVerticalPosition"] = 0.5,
	["ScaleSpotlight"] = 1.2,
	["WidgetsDebuffMode"] = 3,
	["ScaleIgnoreNonEliteUnits"] = false,
	["ClassColorPartyMembers"] = false,
	["ColorAttackingMe"] = {
		["r"] = 0.05882352941176471,
		["g"] = 0.5215686274509804,
		["b"] = 1,
	},
	["OpacityFiltered"] = 0,
	["WidgetsComboPoints"] = true,
	["WidgetsRangeMode"] = 1,
	["WidgetsDebuff"] = true,
	["ClassEnemyIcon"] = false,
}
TidyPlatesHubDamageCache = {
	["OpacitySpotlight"] = 0.5,
	["OpacityTarget"] = 1,
	["ScaleIgnoreNeutralUnits"] = false,
	["ClassPartyIcon"] = false,
	["WidgetsDebuffList"] = {
		["Lacerate"] = true,
		["Rake"] = true,
		["Rip"] = true,
	},
	["ColorAttackingOthers"] = {
		["r"] = 0.6862745098039216,
		["g"] = 1,
		["b"] = 0,
	},
	["OpacityFilterNonElite"] = false,
	["OpacitySpotlightMode"] = 1,
	["OpacityFullNoTarget"] = true,
	["ColorDangerGlowMode"] = 1,
	["WidgetTargetHighlight"] = true,
	["WidgetsThreatIndicator"] = true,
	["TextHealthTextMode"] = 1,
	["WidgetsTotemIcon"] = false,
	["ColorDangerGlowOnParty"] = false,
	["ScaleStandard"] = 1,
	["OpacityNonTarget"] = 0.5,
	["ColorHealthBarMode"] = 3,
	["WidgetsRangeIndicator"] = false,
	["OpacityFilterCustom"] = {
		["Fanged Pit Viper"] = true,
	},
	["ColorAggroTransition"] = {
		["r"] = 1,
		["g"] = 0.4901960784313725,
		["b"] = 0,
	},
	["TextShowLevel"] = false,
	["ScaleSpotlightMode"] = 4,
	["OpacityFilterNeutralUnits"] = false,
	["WidgetEliteIndicator"] = true,
	["WidgetsThreatIndicatorMode"] = 1,
	["OpacityFullSpell"] = false,
	["FrameVerticalPosition"] = 0.5,
	["ScaleSpotlight"] = 1.2,
	["WidgetsDebuffMode"] = 3,
	["ScaleIgnoreNonEliteUnits"] = false,
	["ClassColorPartyMembers"] = false,
	["ColorAttackingMe"] = {
		["r"] = 0.9215686274509803,
		["g"] = 0.1254901960784314,
		["b"] = 0,
	},
	["OpacityFiltered"] = 0,
	["WidgetsComboPoints"] = true,
	["WidgetsRangeMode"] = 1,
	["WidgetsDebuff"] = true,
	["ClassEnemyIcon"] = false,
}
