
GoldArray = {
	["Tolate_Hellscream::Horde"] = 96730,
	["Nohsk_Hellscream::Horde"] = 0,
	["Tamori_ChaosWoW Funserver::Horde"] = 0,
	["VIEWALL"] = false,
	["Japhaar_Hellscream::Horde"] = 67220,
	["VERSION2"] = true,
	["Kabun_Laughing Skull::Alliance"] = 993410,
	["Zik_Zuluhed::Alliance"] = 2640,
	["Irone_Hellscream::Horde"] = 0,
	["INITIALIZED"] = true,
	["Nideyn_Hellscream::Horde"] = 4460,
	["Rudeadyet_Hellscream::Horde"] = 306190,
	["Thunderdome_Laughing Skull::Alliance"] = 780,
	["SORTBYNAME"] = true,
	["Anokank_Hellscream::Horde"] = 0,
	["Barimuri_Hellscream::Horde"] = 6940,
	["Prudey_Laughing Skull::Alliance"] = 1270,
	["DISPLAYGPH"] = true,
	["Tyrela_Hellscream::Horde"] = 91710,
	["Bairra_Alterac valley (PVP - INSTA 70)::Horde"] = 0,
	["Xuyxee_Hellscream::Horde"] = 597980,
	["Ciid_Hellscream::Horde"] = 8444240,
	["Chukk_Hellscream::Horde"] = 398680,
	["Xanaomi_Hellscream::Alliance"] = 6540,
}
